import assert from 'node:assert/strict';
import fs from 'node:fs';
import {matrix106} from './matrix106.js';
import {routeNextQuestion106} from './question-router106.js';
import {titleCandidates108,validateTitle108} from './title108.js';
import {goalGroups76} from './goals76.js';
import {descriptionVariants88} from './description-variants88.js';
import {pdfModel107} from './pdf-model107.js';
import {suggestions108,applySuggestion108} from './spelling108.js';
import {applySubject109} from './subject-selector109.js';

const SUBJECTS=[
 ['القرآن الكريم والدراسات الإسلامية','القرآن الكريم','تلاوة القرآن الكريم'],['اللغة العربية','القراءة','الفهم القرائي'],['الرياضيات','الكسور','توحيد المقامات'],['العلوم','التجارب العلمية','الاستقصاء والتجريب العلمي'],['اللغة الإنجليزية','التواصل','التحدث باللغة الإنجليزية'],['المهارات الرقمية','البرمجة','البرمجة'],['الدراسات الاجتماعية','المواطنة','الهوية الوطنية'],['التربية الفنية','الإنتاج الفني','الإنتاج الفني'],['التربية البدنية','اللياقة البدنية','اللياقة البدنية'],['المهارات الحياتية والأسرية','السلامة الغذائية','السلامة الغذائية'],['النشاط الطلابي','المشاركة الطلابية','المشاركة الطلابية'],['الموهوبون','الإثراء','التفكير الإبداعي']
];
const NAMES=['نورة القحطاني','سلمان الغامدي','عبدالله الشهراني','ريم الحربي','محمد العتيبي','هند الزهراني','فاطمة الدوسري','خالد الزهراني'];
const STAGES=[['ابتدائي','الخامس الابتدائي'],['متوسط','الثاني المتوسط'],['ثانوي','الثاني الثانوي']];
const PROFILES=['غير تقني','متوسط','تقني'];
const FAMILIES=['برنامج / فعالية','اجتماع / متابعة إدارية','تحليل نتائج','خطة','إجراء متابعة','تطوير مهني','شراكة مجتمعية','صيانة وتجهيزات'];
const PLAN=['خطة علاجية','خطة إثرائية','خطة تحسين','خطة تشغيلية'];
const bad=/undefined|\|\|\||__answered|__skill|MeasuredResult|UserChoice|Inference|استجابةً لـ|التخطيط للتحقق منها|تنمية القرآن الكريم/u;
const stats={journeys:0,questions:0,titles:0,goals:0,descriptions:0,pdfs:0,typo:0,mutations:0};
function subtype(f,i){if(f==='خطة')return PLAN[i%4];if(f==='برنامج / فعالية')return['برنامج','فعالية','مبادرة','مسابقة'][i%4];if(f==='اجتماع / متابعة إدارية')return'اجتماع';return''}
function raw(profile,topic,skill,family,name){if(profile==='غير تقني')return`انا ${name} سويت شغله للطلاب عن ${topic} وكان عندهم مشكله، تنفيد العمل في المدرسه والنتايج بنتابعها بعدين`;if(profile==='متوسط')return`نفذت ${family} للطلاب في ${topic} بهدف تحسين ${skill} وسأتابع النتائج بعد التنفيذ`;return`تم تنفيذ ${family} يستهدف ${skill} لدى الطلاب بناء على احتياج محدد مع توثيق التنفيذ والمتابعة`}
function details(f,i){if(f==='برنامج / فعالية')return{reason:'تنمية مهارة محددة',goal:'تنمية المهارات التطبيقية',method:'تطبيق عملي',participation:'تفاعل مرتفع من المستفيدين'};if(f==='اجتماع / متابعة إدارية')return{purpose:'مناقشة نتائج أو بيانات',work:'مراجعة بيانات أو نتائج',product:'اعتماد إجراء محدد',owner:'وكيل المدرسة',follow:'رفع تقرير إنجاز'};if(f==='تحليل نتائج')return{basis:'اختبار تشخيصي',finding:'مهارات منخفضة الإتقان',cause:'صعوبة في مفهوم أو مهارة',action:'إعداد خطة علاجية',follow:'إعادة قياس المهارة',measurement:i%2?'لم يتم القياس بعد':'مقارنة قبل وبعد'};if(f==='خطة')return{basis:'نتائج تقويم أو اختبارات',goal:'معالجة فجوة محددة',method:'تدريب وتطبيق متدرج',owner:'معلم المادة',follow:'متابعة أسبوعية',measurement:i%2?'لم يتم القياس بعد':''};if(f==='إجراء متابعة')return{goal:'إتقان مهارة',method:'سجل متابعة',action:'تقديم دعم إضافي',follow:'إعادة القياس'};if(f==='تطوير مهني')return{need:'احتياج ظهر من تحليل الأداء',method:'ورشة عملية',application:i%2?'لم يبدأ التطبيق بعد':'تطبيق الاستراتيجية في الصف',follow:'مجتمع تعلم مهني'};if(f==='شراكة مجتمعية')return{reason:'دعم تعلم الطلاب',method:'لقاء أو زيارة',participation:'تفاعل مرتفع من المستفيدين'};return{reason:'عطل أو قصور قائم',method:'إجراء صيانة',status:'قيد التنفيذ',follow:'متابعة دورية'}}
function answerAdaptive(s,skill){let qn=0;for(let guard=0;guard<10;guard++){const r=routeNextQuestion106(s,matrix106(s));if(r.done)break;const q=r.question;qn++;assert.ok(q.q&&q.opts?.length>=2,`${s.classification.type}/${q.id}: invalid question`);assert.equal(new Set(q.opts).size,q.opts.length,`${q.id}: duplicate options`);let v=q.opts[0];if(q.id==='skillFocus'&&q.opts.includes(skill))v=skill;s.metadata.familyDetails[q.id]=v}assert.ok(qn<=7,`journey too long: ${qn}`);return qn}
function visible(x,label){x=String(x||'').trim();assert.ok(x.length>4,`${label}: empty`);assert.ok(!bad.test(x),`${label}: bad visible copy -> ${x}`);assert.ok(!/\s{2,}/.test(x),`${label}: repeated spaces`);return x}
for(let i=0;i<36;i++){
 const [subject,topic,skill]=SUBJECTS[i%SUBJECTS.length],[stage,grade]=STAGES[i%3],profile=PROFILES[i%3],family=FAMILIES[i%8],name=NAMES[i%NAMES.length];
 const s={raw:raw(profile,topic,skill,family,name),topic,classification:{type:family,subtype:subtype(family,i)},metadata:{executorName:name,familyDetails:{subject94:subject,...details(family,i)},durationChoice:'أسبوعان',duration:'أسبوعان',placeMode:'داخل المدرسة',place:'قاعة المدرسة',semantic101:{}},audiences:['الطلاب'],stage,grades:[grade],answers:{goals:[],evidence:[]},attachments:[]};
 if(profile!=='غير تقني')s.metadata.familyDetails.skillFocus=skill;
 const qn=answerAdaptive(s,skill);stats.questions+=qn;
 const titles=titleCandidates108(s);assert.ok(titles.length>=1&&titles.length<=3,`${family}: bad title count`);for(const t of titles){visible(t,'title');assert.ok(validateTitle108(t));assert.ok(!t.includes(name),'person name leaked into title');stats.titles++}s.metadata.selectedTitle=titles[0];
 const goals=goalGroups76(s).primary;assert.ok(goals.length>=2&&goals.length<=8,`${family}: goals count`);goals.slice(0,3).forEach(g=>visible(g,'goal'));s.answers.goals=goals.slice(0,2);stats.goals+=goals.length;
 const variants=descriptionVariants88(s);assert.equal(variants.length,4,'must expose four description choices');for(const v of variants){const text=visible(v.text,`${family}/${v.id}`);assert.ok(text.includes(titles[0]),`${family}/${v.id}: title not carried`);if(s.metadata.familyDetails.measurement==='لم يتم القياس بعد')assert.ok(!/تم التحقق من النتيجة/.test(text),'unmeasured result was claimed');stats.descriptions++}s.metadata.generatedDescription=variants[1].text;
 for(const mode of ['color','mono']){const p=pdfModel107(s,{mode});assert.ok(p.sections.length>=3,`${family}/${mode}: weak PDF plan`);const titleSec=p.sections.find(x=>x.def.id==='title');assert.equal(titleSec?.data?.title,titles[0],`${family}/${mode}: PDF title drift`);const visibleData=p.sections.map(x=>JSON.stringify(x.data??'')).join(' ');assert.ok(!bad.test(visibleData),`${family}/${mode}: technical/bad text leaked to visible PDF sections`);stats.pdfs++}
 if(profile==='غير تقني'){const ss=suggestions108(s.raw);for(const word of ['تنفيد','المدرسه','النتايج'])assert.ok(ss.some(x=>x.from===word),`missing spelling suggestion ${word}`);let corrected=s.raw;for(const x of ss)corrected=applySuggestion108(corrected,x.from,x.to);assert.ok(!/تنفيد|المدرسه|النتايج/.test(corrected),'typos survived correction');stats.typo++}
 stats.journeys++;
}
{
 const s={raw:'نفذت برنامج لتحسين القراءة',topic:'القراءة',classification:{type:'برنامج / فعالية',subtype:'برنامج'},metadata:{familyDetails:{subject94:'اللغة العربية',skillFocus:'الفهم القرائي'},selectedTitle:'برنامج تنمية مهارات القراءة',workTitle:'برنامج تنمية مهارات القراءة',titleManual:false,resolvedSkill106:{skill:'الفهم القرائي'}},audiences:['الطلاب'],stage:'متوسط',grades:['الثاني المتوسط'],answers:{goals:['تنمية مهارات القراءة'],evidence:[]}};
 applySubject109(s,'اللغة العربية');applySubject109(s,'الرياضيات');assert.equal(s.metadata.familyDetails.subject94,'الرياضيات');assert.equal(s.metadata.familyDetails.skillFocus,undefined,'stale skill survived subject change');assert.equal(s.metadata.resolvedSkill106,undefined,'stale resolved skill survived subject change');assert.equal(s.metadata.selectedTitle,'','stale generated title survived subject change');assert.deepEqual(s.answers.goals,[],'old goals survived subject change');stats.mutations++;
}
const home=fs.readFileSync(new URL('../home106.html',import.meta.url),'utf8');const app103=fs.readFileSync(new URL('./app103.js',import.meta.url),'utf8');const app89=fs.readFileSync(new URL('./app89.js',import.meta.url),'utf8');const app88=fs.readFileSync(new URL('./app88.js',import.meta.url),'utf8');const ws=fs.readFileSync(new URL('./workspace109.js',import.meta.url),'utf8');
assert.ok(/name="viewport"/.test(home),'mobile viewport missing');const token=home.match(/app103\.js\?v=([^"']+)/)?.[1];assert.ok(token,'entry cache token missing');assert.ok(app103.includes(`app89.js?v=${token}`),'app103 cache token drift');assert.ok(app89.includes(`app88.js?v=${token}`),'app89 cache token drift');
// V113 keeps the production entry chain on the current token, while unchanged V112 description modules remain deliberately pinned to their validated build. cache111-tests.js is the authoritative dependency-edge gate.
assert.ok(app88.includes('description-ui88.js?v=112'),'description-ui88.js validated pin drift');assert.ok(app88.includes('description-variants88.js?v=112'),'description-variants88.js validated pin drift');
assert.ok(/@media\(max-width:700px\)/.test(ws),'workspace mobile breakpoint missing');for(const x of ['الرئيسية','السابق','التالي','الأرشيف والملفات'])assert.ok(ws.includes(x),`workspace navigation missing ${x}`);
console.log(`V110.2 acceptance PASS: ${stats.journeys} deep journeys, ${stats.questions} adaptive questions, ${stats.titles} titles, ${stats.goals} goals, ${stats.descriptions} visible descriptions, ${stats.pdfs} PDF models, ${stats.typo} typo-heavy journeys, ${stats.mutations} change-of-mind mutation checks.`);
