const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const clean=s=>String(s||'').replace(/\s+/g,' ').trim();
const mem={get(k){try{return sessionStorage.getItem('v94_'+k)||''}catch{return''}},set(k,v){try{sessionStorage.setItem('v94_'+k,String(v||''))}catch{}}};
function subject(){return mem.get('subjects').split('|||').filter(Boolean)[0]||''}
function raw(){return mem.get('raw')||''}
function topic(){const r=raw();const P=[[/خط|كتابة/,'الخط والكتابة'],[/قراء|فهم قرائي/,'القراءة والفهم القرائي'],[/كسور/,'الكسور'],[/جدول الضرب|الضرب/,'جدول الضرب'],[/معادلات/,'المعادلات'],[/تجرب|مختبر/,'التجارب والاستقصاء العلمي'],[/مفردات|vocabulary/i,'المفردات'],[/تحدث|speaking/i,'التحدث'],[/استماع|listening/i,'الاستماع'],[/امن|أمن|سلامة|إخلاء/,'الأمن والسلامة'],[/وطن|هوية/,'الهوية الوطنية'],[/سلوك|انضباط/,'السلوك والانضباط']];for(const[p,t] of P)if(p.test(r))return t;return''}
function profile(){const s=subject(),t=topic();if(/العربية|كفايات|لغوية/.test(s))return{reasons:t==='الخط والكتابة'?['تنمية مهارات الخط والكتابة','معالجة ضعف في وضوح الخط وتنظيم الكتابة','رفع مستوى العناية بجودة الكتابة','تعزيز الدافعية نحو تحسين الخط','دعم مهارات التعبير الكتابي']:t.includes('القراءة')?['تنمية الطلاقة القرائية','رفع مستوى الفهم القرائي','معالجة ضعف في مهارات القراءة','رفع دافعية الطلاب للقراءة','دعم الطلاب المتعثرين قرائيًا']:['تنمية المهارات اللغوية','معالجة احتياج لغوي محدد','رفع مستوى الفهم والتطبيق','تعزيز الممارسة اللغوية','دعم الطلاب المتعثرين'],methods:t==='الخط والكتابة'?['تدريبات خطية موجهة','عرض نماذج للخط الصحيح','تطبيق فردي','أنشطة جماعية','مقارنة نماذج قبل وبعد','مسابقة في جودة الخط']:['نمذجة وتطبيق موجه','قراءة أو تطبيق فردي','أنشطة جماعية','تدريب متدرج','مناقشة وتغذية راجعة','تقويم قصير'],notes:t==='الخط والكتابة'?['تحسن في وضوح الخط','تحسن في الالتزام بالسطر والمسافات','تفاوت في مستوى الطلاب','حاجة بعض الطلاب إلى تدريب إضافي','تحسن في سرعة وجودة الكتابة']:['تحسن في الأداء اللغوي','تفاوت بين مستويات الطلاب','زيادة المشاركة','استمرار احتياج بعض الطلاب للدعم','تحسن في التطبيق']};
if(/رياضيات/.test(s))return{reasons:['معالجة ضعف في فهم المهارة الرياضية','معالجة أخطاء متكررة في الحل','رفع مستوى الإتقان','دعم الطلاب المتعثرين','ربط المفهوم بالتطبيق'],methods:['أمثلة محلولة','مسائل متدرجة','تطبيق فردي','مجموعات تعلم','مسائل حياتية','ألعاب تعليمية','تقويم قصير أثناء التنفيذ'],notes:['تحسن دقة الحل','تفاوت في سرعة الاستيعاب','استمرار أخطاء لدى بعض الطلاب','تحسن في تطبيق المهارة','حاجة إلى إعادة تدريب جزئي']};
if(/علوم|أحياء|كيمياء|فيزياء/.test(s))return{reasons:['تنمية الفهم العلمي','تنمية مهارات الاستقصاء والملاحظة','ربط المفهوم بالتطبيق العملي','معالجة صعوبة في مفهوم علمي','تعزيز مهارات التجريب الآمن'],methods:['تجربة عملية','ملاحظة واستقصاء','عرض نموذج علمي','عمل مجموعات','تسجيل النتائج وتفسيرها','مناقشة علمية','تقويم تطبيقي'],notes:['تحسن في تفسير النتائج','تفاعل مرتفع أثناء التطبيق العملي','تفاوت في مهارات الاستقصاء','حاجة بعض الطلاب إلى دعم إضافي','تحسن في استخدام الأدوات والإجراءات']};
if(/إنجليزية/.test(s))return{reasons:['تنمية مهارات اللغة الإنجليزية','رفع الثروة اللغوية','معالجة ضعف في مهارة لغوية محددة','رفع الثقة في التواصل','زيادة الممارسة الفعلية للغة'],methods:['محادثة موجهة','تدريب على المفردات','استماع وتطبيق','قراءة موجهة','كتابة قصيرة','عمل أزواج أو مجموعات','نشاط تفاعلي'],notes:['تحسن في المشاركة باللغة الإنجليزية','تحسن في النطق أو المفردات','تفاوت في الطلاقة','حاجة بعض الطلاب إلى ممارسة إضافية','ارتفاع الثقة في التواصل']};return null}
function replaceOptions(group,id,opts){const hidden=$(`[data-family-field="${id}"]`,group),grid=$('.choiceGrid',group);if(!hidden||!grid||!opts?.length)return;const sig=`${subject()}|${topic()}|${id}`;if(group.dataset.v95sig===sig)return;group.dataset.v95sig=sig;hidden.value='';grid.innerHTML=opts.map(x=>`<button type="button" class="chip" data-family-pick="${id}" data-family-value="${x}">${x}</button>`).join('')}
function adaptDetails(root){const p=profile();if(!p)return;$$('.familyChoice',root).forEach(g=>{const h=$('[data-family-field]',g);if(!h)return;const id=h.dataset.familyField;if(id==='reason')replaceOptions(g,id,p.reasons);else if(id==='method')replaceOptions(g,id,p.methods);else if(id==='participation')replaceOptions(g,id,p.notes)})}
function goalSet(){const s=subject(),t=topic();if(/العربية|كفايات|لغوية/.test(s)){if(t==='الخط والكتابة')return['تحسين وضوح الخط وتنظيم الكتابة لدى الطلاب','تنمية قدرة الطلاب على تطبيق قواعد الخط والكتابة بدقة','تعزيز العناية بجودة الكتابة وإخراجها'];if(t.includes('القراءة'))return['رفع مستوى الطلاقة والفهم القرائي','تنمية قدرة الطلاب على فهم النصوص وتحليلها','تعزيز الدافعية نحو القراءة المستمرة'];return['تنمية المهارات اللغوية المستهدفة','رفع مستوى التطبيق اللغوي الصحيح','تعزيز الثقة في استخدام اللغة']}if(/رياضيات/.test(s))return[`رفع مستوى إتقان ${t||'المهارة الرياضية'} لدى الطلاب`,`تنمية القدرة على تطبيق ${t||'المهارات الرياضية'} في مواقف متنوعة`,'تقليل الأخطاء المتكررة وتحسين دقة الحل'];if(/علوم|أحياء|كيمياء|فيزياء/.test(s))return[`تنمية الفهم العلمي المرتبط بـ${t||s}`,'تنمية مهارات الاستقصاء والملاحظة والتجريب','ربط المفاهيم العلمية بالتطبيق العملي'];if(/إنجليزية/.test(s))return[`تنمية مهارات اللغة الإنجليزية المرتبطة بـ${t||'موضوع العمل'}`,'رفع مستوى الثقة في التواصل باللغة الإنجليزية','زيادة الممارسة الفعلية للمهارة المستهدفة'];return[]}
function rebuildGoals(root){const h=$('h1',root);if(!h||clean(h.textContent)!=='الأهداف')return;const card=h.closest('.card')||root,sig=`${subject()}|${topic()}`;if(card.dataset.v95Goals===sig)return;const base=goalSet();if(!base.length)return;card.dataset.v95Goals=sig;const grid=$('[data-goal]',card)?.parentElement;if(!grid)return;grid.innerHTML=base.map((g,i)=>`<button type="button" class="chip ${i===0?'v95PrimaryGoal':''}" data-goal="${g}">${g}</button>`).join('');$$('details',card).forEach(d=>d.remove());$$('.v92More,.v94MoreGoals',card).forEach(x=>x.remove())}
function formalTopic(t){if(t==='الخط والكتابة')return'تحسين مهارات الخط والكتابة';if(t==='القراءة والفهم القرائي')return'تنمية مهارات القراءة والفهم القرائي';if(t==='جدول الضرب')return'تنمية مهارات جدول الضرب';if(t==='الكسور')return'تنمية مهارات الكسور';if(t==='المعادلات')return'تنمية مهارات حل المعادلات';if(t==='التجارب والاستقصاء العلمي')return'تنمية مهارات التجريب والاستقصاء العلمي';if(t==='المفردات')return'تنمية الثروة اللغوية والمفردات';if(t==='التحدث')return'تنمية مهارات التحدث';if(t==='الاستماع')return'تنمية مهارات الاستماع';return t}
function titleSet(){const s=subject(),t=topic()||s||'العمل المستهدف',sub=mem.get('subtype')||'برنامج';if(mem.get('family')!=='برنامج / فعالية')return[];const formal=`${sub} ${formalTopic(t)}`,direct=t,creative=t==='الخط والكتابة'?(sub==='مسابقة'?'أجمل خط':sub==='مبادرة'?'خطي أجمل':'خطي أجمل'):t.includes('القراءة')?(sub==='مسابقة'?'قارئ متميز':'أقرأ بطلاقة'):t==='جدول الضرب'?(sub==='مسابقة'?'أبطال الضرب':'أتقن الضرب'):t==='الكسور'?'أبطال الكسور':(/علوم|التجارب/.test(t)||/علوم/.test(s))?(sub==='مسابقة'?'تحدي العالم الصغير':'مختبري الصغير'):'';return[formal,direct,creative].filter(Boolean)}
function rebuildTitle(root){const h=$('h1',root);if(!h||clean(h.textContent)!=='عنوان الوثيقة')return;const card=h.closest('.card')||root,sig=`${subject()}|${topic()}|${mem.get('subtype')}`;if(card.dataset.v95Title===sig)return;const titles=titleSet();if(!titles.length)return;card.dataset.v95Title=sig;const old=$('.titleChoices94,.recommendedTitle',card);if(old)old.outerHTML=`<div class="titleChoices94">${titles.map((x,i)=>`<button class="titleChoice94 ${i===0?'primary94':''}" data-title-accept="${x}"><small>${['موصى به للتوثيق','مختصر وواضح','عنوان جاذب'][i]}</small><b>${x}</b></button>`).join('')}</div>`}
function rerun(root){adaptDetails(root);rebuildGoals(root);rebuildTitle(root)}
export function installAdaptive95(root=document){document.addEventListener('click',e=>{if(e.target.closest('[data-subject94]'))setTimeout(()=>rerun(root),0)},true);new MutationObserver(()=>requestAnimationFrame(()=>rerun(root))).observe(root,{childList:true,subtree:true});rerun(root)}
