import {esc} from './engine.js';
const arDigits=s=>String(s??'').replace(/[٠-٩]/g,d=>'٠١٢٣٤٥٦٧٨٩'.indexOf(d)).replace(/[۰-۹]/g,d=>'۰۱۲۳۴۵۶۷۸۹'.indexOf(d));
const clean=v=>String(v??'').trim();
export function parseAnalysisRows113(raw,maxScore=0){const rows=String(raw||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean),scores=[],names=[],invalid=[];for(const row of rows){const normalized=arDigits(row).replace(/\t/g,' ').replace(/[،,;]/g,' ').replace(/\s+/g,' ').trim();const parts=normalized.split(' ');let scoreIndex=-1,score=null;for(let i=parts.length-1;i>=0;i--){const n=Number(parts[i]);if(Number.isFinite(n)){scoreIndex=i;score=n;break}}if(scoreIndex<0||score===null||(Number(maxScore)>0&&(score<0||score>Number(maxScore)))){invalid.push(row);continue}scores.push(score);names.push(parts.slice(0,scoreIndex).join(' ').trim())}return{scores,names,invalid,count:scores.length}}
export function analysisState113(state){state.metadata=state.metadata||{};state.metadata.analysis=state.metadata.analysis||{maxScore:'',scores:[],names:[],rawRows:''};return state.metadata.analysis}
export function analysisFinding113(state){const a=analysisState113(state),scores=(a.scores||[]).map(Number).filter(Number.isFinite),max=Number(a.maxScore||0);if(!scores.length||!max)return'';const avg=scores.reduce((x,y)=>x+y,0)/scores.length,achievement=avg/max*100,low=scores.filter(x=>x/max<.5).length,advanced=scores.filter(x=>x/max>=.9).length;return `شمل التحليل ${scores.length} طالبًا، وبلغ متوسط الدرجات ${avg.toFixed(2)} من ${max} بنسبة تحصيل ${achievement.toFixed(1)}٪، مع ${low} في مستوى يحتاج تدخلًا مباشرًا و${advanced} في مستوى متقدم.`}
export function analysisSummary113(state){const a=analysisState113(state),scores=(a.scores||[]).map(Number).filter(Number.isFinite),max=Number(a.maxScore||0);if(!scores.length||!max)return{ready:false,count:scores.length,maxScore:max};const sum=scores.reduce((x,y)=>x+y,0),avg=sum/scores.length,sorted=[...scores].sort((x,y)=>x-y),mid=Math.floor(sorted.length/2),median=sorted.length%2?sorted[mid]:(sorted[mid-1]+sorted[mid])/2;return{ready:true,count:scores.length,maxScore:max,sum,avg,median,high:Math.max(...scores),low:Math.min(...scores),achievement:avg/max*100,weak:scores.filter(x=>x/max<.5).length,monitor:scores.filter(x=>x/max>=.5&&x/max<.7).length,advanced:scores.filter(x=>x/max>=.9).length}}
function commit(state,maxScore,rawRows){const a=analysisState113(state);a.maxScore=clean(maxScore);a.rawRows=String(rawRows||'');const parsed=parseAnalysisRows113(rawRows,a.maxScore);a.scores=parsed.scores;a.names=parsed.names;a.invalid=parsed.invalid;a.updatedAt=Date.now();state.metadata.count=String(parsed.count||'');state.metadata.countSource101='derived';state.metadata.familyDetails=state.metadata.familyDetails||{};const finding=analysisFinding113(state);if(finding){state.metadata.familyDetails.finding=finding;state.metadata.analysis.findingSource='derived'}return parsed}
export function analysisDataPending113(state){if(state?.classification?.type!=='تحليل نتائج')return false;return !analysisSummary113(state).ready}
export function analysisDataPanel113(state){if(state?.classification?.type!=='تحليل نتائج')return'';const a=analysisState113(state),sum=analysisSummary113(state);if(sum.ready&&!state.metadata?.editAnalysisData113)return `<section class="analysisData113 analysisDataReady113"><div><small>بيانات النتائج</small><b>${sum.count} طالبًا · الدرجة الكلية ${sum.maxScore} · متوسط ${sum.avg.toFixed(2)}</b><p>تم حساب العدد والمؤشرات من الدرجات نفسها؛ لن يطلبها النظام منك مرة أخرى.</p></div><button type="button" class="linkBtn" data-analysis-edit113>تعديل الدرجات</button></section>`;return `<section class="analysisData113" data-analysis-host113><div class="adaptiveKicker106">بيانات التحليل — إدخال مرة واحدة</div><h2>ألصق درجات الطلاب</h2><p class="questionHelp">يمكن لصق عمود الدرجات مباشرة من Excel، أو كتابة «اسم الطالب 35». عدد الطلاب سيُحسب تلقائيًا.</p><label class="fullField"><span>الدرجة الكلية للاختبار</span><input data-analysis-max113 inputmode="decimal" value="${esc(a.maxScore||'')}" placeholder="مثال: 40"></label><label class="fullField"><span>الدرجات</span><textarea data-analysis-rows113 rows="8" placeholder="35\n28\n40\n...">${esc(a.rawRows||'')}</textarea></label><div data-analysis-feedback113 class="questionHelp">${sum.count?`تم التعرف على ${sum.count} درجة.`:'لن يظهر حقل منفصل لعدد الطلاب.'}</div><div class="row adaptiveActions106"><button type="button" class="btn primary" data-analysis-next113 ${sum.ready?'':'disabled'}>اعتماد الدرجات والمتابعة</button>${sum.ready?'<button type="button" class="btn" data-analysis-cancel113>إلغاء التعديل</button>':''}</div></section>`}
let current=null;
export function bindAnalysisData113(state){current=state;queueMicrotask(renderAnalysisSlot113)}
function signal(){const carrier=document.querySelector('[data-adaptive-zone] [data-family-field]');if(carrier)carrier.dispatchEvent(new Event('input',{bubbles:true}))}
export function renderAnalysisSlot113(){if(!current||typeof document==='undefined')return;const slot=document.querySelector('[data-analysis-slot113]'),zone=document.querySelector('[data-adaptive-zone]'),metaPending=Boolean(document.querySelector('[data-family-meta-host111]'));if(!slot)return;if(current.classification?.type!=='تحليل نتائج'){slot.innerHTML='';slot.hidden=true;if(zone)zone.hidden=metaPending;return}slot.hidden=metaPending;if(!metaPending)slot.innerHTML=analysisDataPanel113(current);if(zone)zone.hidden=metaPending||analysisDataPending113(current)||Boolean(current.metadata?.editAnalysisData113)}
if(typeof document!=='undefined'){
 document.addEventListener('family-meta-change111',renderAnalysisSlot113,true);
 document.addEventListener('input',e=>{if(!current)return;if(!e.target.matches('[data-analysis-max113],[data-analysis-rows113]'))return;const host=e.target.closest('[data-analysis-host113]'),max=host?.querySelector('[data-analysis-max113]')?.value||'',rows=host?.querySelector('[data-analysis-rows113]')?.value||'',p=commit(current,max,rows),fb=host?.querySelector('[data-analysis-feedback113]'),next=host?.querySelector('[data-analysis-next113]');if(fb)fb.textContent=p.invalid.length?`تم التعرف على ${p.count} درجة، وهناك ${p.invalid.length} سطر يحتاج مراجعة.`:`تم التعرف على ${p.count} درجة. عدد الطلاب = ${p.count}.`;if(next)next.disabled=!(p.count&&Number(max)>0)},true);
 document.addEventListener('click',e=>{if(!current)return;if(e.target.closest('[data-analysis-edit113]')){current.metadata.editAnalysisData113=true;renderAnalysisSlot113();return}if(e.target.closest('[data-analysis-cancel113]')){current.metadata.editAnalysisData113=false;renderAnalysisSlot113();return}const next=e.target.closest('[data-analysis-next113]');if(next&&!next.disabled){current.metadata.editAnalysisData113=false;signal();renderAnalysisSlot113()}},true)
}