import {normalizedNumberText120,finiteNumber120,positiveInteger120} from './input-normalization120.js';
const arDigits=normalizedNumberText120;
let expectedCount=0;
function parseRows(raw,max){const scores=[];for(const row of String(raw||'').split(/\r?\n/).map(x=>x.trim()).filter(Boolean)){let x=arDigits(row).replace(/[؛;،\t]/g,' ').replace(/\s+/g,' ').trim();x=x.replace(/(\d),(\d)/g,'$1.$2');const m=x.match(/(?:^|[\s,])([+-]?(?:\d+(?:\.\d+)?|\.\d+))\s*$/),n=m?finiteNumber120(m[1]):null;if(n!==null&&n>=0&&(!max||n<=max))scores.push(n)}return scores}
function values(host){const max=finiteNumber120(host.querySelector('[data-analysis-max113]')?.value)||0;let scores=[];const area=host.querySelector('[data-analysis-rows113]');if(area)scores=parseRows(area.value,max);else scores=[...host.querySelectorAll('[data-analysis-score114]')].map(x=>finiteNumber120(x.value)).filter(n=>n!==null&&n>=0&&(!max||n<=max));return{max,scores}}
function metric(label,value){return `<div><small>${label}</small><b>${value}</b></div>`}
function consistency(live,actual){let box=live.nextElementSibling;if(!box?.classList?.contains('analysisConsistency116')){box=document.createElement('div');live.insertAdjacentElement('afterend',box)}box.className='analysisConsistency116';if(!expectedCount){box.classList.add('ok116');box.innerHTML=`<b>عدد الطلاب تلقائي</b><span>سيُحسب عدد الطلاب تلقائيًا من الدرجات المدخلة (${actual}).</span>`;return}if(actual===expectedCount){box.classList.add('ok116');box.innerHTML=`<b>✓ اكتمال الدرجات</b><span>مكتمل: تم إدخال ${actual} درجة من أصل ${expectedCount} طالبًا.</span>`;return}box.classList.add('warn116');if(actual<expectedCount){const diff=expectedCount-actual;box.innerHTML=`<b>⚠ تحقق من العدد</b><span>تنبيه: عدد طلاب الفصل ${expectedCount}، بينما أُدخلت ${actual} درجة فقط. توجد ${diff} درجة ناقصة ويمكنك المتابعة أو استكمالها.</span>`;return}const diff=actual-expectedCount;box.innerHTML=`<b>⚠ تحقق من العدد</b><span>تنبيه: أُدخلت ${actual} درجة بينما عدد طلاب الفصل المسجل ${expectedCount}. توجد ${diff} درجة زائدة؛ راجع العدد أو الدرجات.</span>`}
function refresh(host){const live=host?.querySelector('.analysisLive114');if(!live)return;expectedCount=positiveInteger120(host.querySelector('[data-analysis-expected118]')?.value)||expectedCount||0;const {max,scores}=values(host);if(!scores.length||!max){live.className='analysisLive114 empty';live.innerHTML='<span>ابدأ بكتابة أول درجة</span><small>سيظهر العدد والمتوسط والتحصيل مباشرة.</small>';consistency(live,scores.length);return}const sum=scores.reduce((a,b)=>a+b,0),avg=sum/scores.length,achievement=avg/max*100;live.className='analysisLive114';live.innerHTML=metric('الطلاب',scores.length)+metric('المتوسط',avg.toFixed(2))+metric('التحصيل',achievement.toFixed(1)+'٪')+metric('الأعلى',Math.max(...scores))+metric('الأدنى',Math.min(...scores));consistency(live,scores.length)}
if(typeof document!=='undefined'){
 document.addEventListener('input',e=>{if(e.target.matches?.('[data-family-meta111="expectedCount"],[data-analysis-expected118]'))expectedCount=positiveInteger120(e.target.value)||0;const host=e.target.closest?.('[data-analysis-host113]');if(!host)return;if(e.target.matches('[data-analysis-max113],[data-analysis-mastery120],[data-analysis-expected118],[data-analysis-rows113],[data-analysis-name114],[data-analysis-score114]'))queueMicrotask(()=>refresh(host))},true);
 document.addEventListener('click',e=>{const host=e.target.closest?.('[data-family-meta-host111][data-field111="expectedCount"]');if(!host)return;const input=host.querySelector('[data-family-meta111="expectedCount"]');if(input)expectedCount=Math.max(0,Number(arDigits(input.value))||0)},true);
}
