import {chromium} from 'playwright';
import assert from 'node:assert/strict';
const base='http://127.0.0.1:4173/home106.html?v=117';
const scenarios=[
 {name:'هاتف-فعالية',viewport:{width:390,height:844},raw:'سويت فعاليه لتحسين القراءه للطلاب وكان عندهم ضعف وابي اوثق التنفيد والنتايج',family:'برنامج / فعالية',stage:'ابتدائي'},
 {name:'هاتف-تحليل',viewport:{width:390,height:844},raw:'حللت نتايج اختبار الرياضيات وظهر ضعف في الكسور وبسوي اجراء علاجي',family:'تحليل نتائج',stage:'متوسط',analysis:true},
 {name:'هاتف-خطة',viewport:{width:430,height:932},raw:'ابي اوثق خطه علاجيه لطلاب عندهم ضعف في القراءه',family:'خطة',stage:'متوسط'},
 {name:'سطح-اجتماع',viewport:{width:1366,height:900},raw:'عقدنا اجتماع لمناقشة نتائج الطلاب وتحديد الاجراءات والمسؤوليات والمتابعة',family:'اجتماع / متابعة إدارية',stage:'ثانوي'},
 {name:'سطح-تطوير',viewport:{width:1440,height:900},raw:'حضرت ورشه تطوير مهني عن استراتيجيات التدريس ولم يبدأ التطبيق بعد',family:'تطوير مهني',stage:'متوسط'},
 {name:'سطح-متابعة',viewport:{width:1280,height:800},raw:'تابعت تنفيذ الخطة مع الطلاب وسجلت مستوى التقدم وحددت من يحتاج دعما اضافيا واعادة قياس',family:'إجراء متابعة',stage:'ابتدائي'}
];
async function clickIf(page,selector){const l=page.locator(selector).first();if(await l.count()&&await l.isVisible()){await l.click();return true}return false}
async function chooseFamily(page,family){const l=page.locator('[data-type]').filter({hasText:family}).first();assert.ok(await l.count(),`family button missing: ${family}`);await l.click()}
async function fillFamilyMeta111(page,name){for(let guard=0;guard<8;guard++){const host=page.locator('[data-family-meta-host111]').first();if(!(await host.count())||!(await host.isVisible()))break;const choice=host.locator('[data-family-meta-choice111]').first();if(await choice.count())await choice.click();else{const input=host.locator('[data-family-meta111]').first();assert.ok(await input.count(),`${name}: family metadata control missing`);const type=await input.getAttribute('type');const value=type==='number'?'8':type==='date'?'2026-08-20':type==='time'?'09:00':'بيان موثق للاختبار';await input.fill(value)}const next=host.locator('[data-family-meta-next111]');assert.ok(await next.count(),`${name}: family metadata next missing`);await next.click()}assert.equal(await page.locator('[data-family-meta-host111]').count(),0,`${name}: family metadata flow did not finish`)}
async function fillAnalysisData113(page,name){const host=page.locator('[data-analysis-host113]').first();assert.ok(await host.count(),`${name}: analysis score input missing`);assert.ok(await host.isVisible(),`${name}: analysis score input hidden unexpectedly`);await host.locator('[data-analysis-max113]').fill('40');await host.locator('[data-analysis-rows113]').fill('35\n28\n40\n31\n20\n18\n37\n33');const studentMetric=host.locator('.analysisLive114>div').filter({hasText:'الطلاب'}).first();assert.ok(await studentMetric.count(),`${name}: live student count metric missing`);assert.equal((await studentMetric.locator('b').textContent())?.trim(),'8',`${name}: student count was not derived from scores`);const next=host.locator('[data-analysis-next113]');assert.ok(!(await next.isDisabled()),`${name}: score acceptance remained disabled`);await next.click();await page.waitForTimeout(80);assert.equal(await page.locator('[data-analysis-host113]').count(),0,`${name}: analysis score flow did not finish`);assert.ok(await page.locator('.analysisDataReady113').count(),`${name}: derived analysis summary missing`)}
async function overflowDiagnostics(page){return page.evaluate(()=>{const vw=document.documentElement.clientWidth;return [...document.querySelectorAll('body *')].map(el=>{const r=el.getBoundingClientRect();return{tag:el.tagName.toLowerCase(),cls:el.className||'',id:el.id||'',left:Math.round(r.left),right:Math.round(r.right),width:Math.round(r.width),scrollWidth:el.scrollWidth,clientWidth:el.clientWidth}}).filter(x=>x.right>vw+2||x.left<-2||x.scrollWidth>x.clientWidth+2).sort((a,b)=>Math.max(b.right-vw,b.scrollWidth-b.clientWidth)-Math.max(a.right-vw,a.scrollWidth-a.clientWidth)).slice(0,12)})}
async function runScenario(browser,s){const context=await browser.newContext({viewport:s.viewport,locale:'ar-SA'});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(String(e)));await page.goto(base,{waitUntil:'networkidle'});assert.ok(await page.locator('.workspace109').isVisible(),`${s.name}: workspace missing`);assert.ok(await page.getByText('وثّق عملك بسهولة').isVisible(),`${s.name}: home missing`);await page.locator('[data-entry="smart"]').first().click();await page.locator('#raw').fill(s.raw);await page.locator('[data-action="analyze"]').click();const date=page.locator('#dateISO');assert.ok(await date.count(),`${s.name}: date control missing`);assert.ok((await date.inputValue()).length===10,`${s.name}: date was not initialized automatically`);await chooseFamily(page,s.family);if(!(await page.locator('[data-audience="الطلاب"].on').count()))await page.locator('[data-audience="الطلاب"]').click();await page.locator(`[data-stage="${s.stage}"]`).click();const grade=page.locator('[data-grade]').first();assert.ok(await grade.count(),`${s.name}: grades missing`);await grade.click();await page.locator('[data-action="go-goals"]').click();
 await clickIf(page,'[data-subject109]');
 await fillFamilyMeta111(page,s.name);
 if(s.analysis)await fillAnalysisData113(page,s.name);
 for(let guard=0;guard<9;guard++){const q=page.locator('[data-adaptive-question]');if(!(await q.count())||!(await q.isVisible()))break;const pick=q.locator('[data-adaptive-pick]').first();assert.ok(await pick.count(),`${s.name}: adaptive choice missing`);await pick.click();await q.locator('[data-adaptive-continue]').click();}
 assert.ok(await page.locator('[data-action="family-details-next"]').count(),`${s.name}: adaptive flow did not finish`);
 if(s.name==='هاتف-فعالية'){await page.locator('[data-ws109="prev"]').click();assert.ok(await page.getByText('راجع ما فهمه المحرك').isVisible(),'previous navigation failed');await page.locator('[data-ws109="next"]').click();assert.ok(await page.locator('[data-action="family-details-next"]').count(),'next navigation failed');}
 await page.locator('[data-action="family-details-next"]').click();const goal=page.locator('[data-goal]').first();assert.ok(await goal.count(),`${s.name}: no goals`);await goal.click();await page.locator('[data-action="go-description"]').click();const title=page.locator('[data-title-accept]').first();assert.ok(await title.count(),`${s.name}: title recommendation missing`);await title.click();await page.locator('[data-description-variant="medium"]').click();assert.ok((await page.locator('#generatedDescription').inputValue()).length>30,`${s.name}: description too short`);await page.locator('[data-action="go-evidence"]').click();
 for(let guard=0;guard<12;guard++){const fix=page.locator('[data-spell76-from]').first();if(!(await fix.count()))break;await fix.click();}
 if(await page.locator('[data-action="go-evidence-direct"]').count())await page.locator('[data-action="go-evidence-direct"]').click();else throw new Error(`${s.name}: spelling review remained blocked`);
 await clickIf(page,'[data-evidence]');await page.locator('[data-action="finalize"]').first().click();await page.waitForSelector('[data-pdf-preview-host107]');assert.ok(await page.getByText('معاينة الوثيقة قبل الطباعة').isVisible(),`${s.name}: PDF preview missing`);if(s.analysis){const print=page.locator('[data-pdf-print107]').first();assert.ok(await print.count(),`${s.name}: print button missing`);assert.ok(await page.locator('.pdfSheet107').count(),`${s.name}: printable analysis sheet missing`);await page.evaluate(()=>{window.__v113PrintCalled=0;window.print=()=>{window.__v113PrintCalled++}});await print.click();assert.equal(await page.evaluate(()=>window.__v113PrintCalled),1,`${s.name}: print action did not call window.print`)}await page.waitForTimeout(500);const archiveButton=page.locator('[data-ws109="archive"]');assert.ok(await archiveButton.isVisible(),`${s.name}: archive button hidden`);await archiveButton.click();await page.waitForSelector('.archive109Card',{state:'visible',timeout:5000});assert.ok(await page.getByText('الأرشيف والملفات المحفوظة').isVisible(),`${s.name}: archive did not open`);await page.waitForFunction(()=>document.querySelectorAll('.archive109Row').length>=1,null,{timeout:5000});const rows=page.locator('.archive109Row');assert.ok(await rows.count()>=1,`${s.name}: final document not archived`);assert.equal(errors.length,0,`${s.name}: browser errors: ${errors.join(' | ')}`);const bodyWidth=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,client:document.documentElement.clientWidth}));if(bodyWidth.scroll>bodyWidth.client+2){const offenders=await overflowDiagnostics(page);assert.fail(`${s.name}: horizontal overflow ${bodyWidth.scroll}/${bodyWidth.client}; offenders=${JSON.stringify(offenders)}`)}await context.close();return true}
const browser=await chromium.launch({headless:true});let passed=0;try{for(const s of scenarios){await runScenario(browser,s);passed++;console.log(`✓ ${s.name}`)}}finally{await browser.close()}console.log(`V117 real browser acceptance PASS: ${passed}/${scenarios.length} end-to-end journeys across mobile and desktop; analysis verifies automatic date, derived student count and working print action.`);
