import {SUBJECTS94,ICONS94,SUBJECT_DECISION94,SCHOOL_GENERAL94} from './subject-registry94.js?v=94';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const clean=s=>String(s||'').replace(/\s+/g,' ').trim();
const mem={get(k){try{return sessionStorage.getItem('v94_'+k)||''}catch{return''}},set(k,v){try{sessionStorage.setItem('v94_'+k,String(v||''))}catch{}}};
const academic=/قراءة|قراءه|خط|كتابة|رياضيات|علوم|انجليزي|إنجليزي|عربي|لغتي|كسور|ضرب|جمع|طرح|معادلات|تجربة|مختبر|فيزياء|كيمياء|أحياء|رقمي|حاسب|اختبار|تحصيل|مهارة|مهارات|درس|منهج|صف/;
const general=/سلامة|امن|أمن|إخلاء|وطني|هوية|سلوك|انضباط|نشاط طلابي|توجيه|إرشاد|أسرة|مجتمع|بيئة|إعاقة/;
function gradeName(v){const x=clean(v);for(const n of ['الأول','الثاني','الثالث','الرابع','الخامس','السادس'])if(x.includes(n))return n;return''}
function stageName(v){const x=clean(v);if(x.includes('ابتد'))return'ابتدائي';if(x.includes('متوسط'))return'متوسط';if(x.includes('ثانو'))return'ثانوي';return''}
function family(){return mem.get('family')}
function raw(){return mem.get('raw')}
function subjectList(){const stage=mem.get('stage')||'متوسط',g=gradeName(mem.get('grade'))||'الأول';if(stage==='ثانوي'){const key=mem.get('track')||'الأولى المشتركة';return SUBJECTS94.ثانوي[key]||SUBJECTS94.ثانوي['الأولى المشتركة']}return SUBJECTS94[stage]?.[g]||SUBJECTS94.متوسط['الأول']}
function shouldShowSubject(){const f=family(),r=raw(),sub=mem.get('subtype'),rule=SUBJECT_DECISION94[f];if(!rule)return false;if(rule.when==='always')return true;if(f==='برنامج / فعالية')return academic.test(r)||!general.test(r);if(f==='خطة')return /علاج|إثراء|تحسين|تطوير/.test(sub)||academic.test(r);if(f==='تطوير مهني')return /تخصص|معلم|معلمين|تدريس/.test(r);return academic.test(r)}
function selectedSubjects(){return mem.get('subjects').split('|||').filter(Boolean)}
function subjectCard(){const rule=SUBJECT_DECISION94[family()]||{},selected=selectedSubjects(),list=subjectList(),multi=rule.multi!==false;const btn=x=>`<button type="button" class="subject94 ${selected.includes(x)?'on':''}" data-subject94="${x}"><span>${ICONS94[x]||'📘'}</span><b>${x}</b></button>`;const general=family()==='برنامج / فعالية'?`<button type="button" class="subject94 general94 ${mem.get('schoolGeneral')?'on':''}" data-general94="1"><span>🏫</span><b>عمل مدرسي عام</b></button>`:'';return `<section class="subjectBlock94" data-subject-multi="${multi?'1':'0'}"><div class="subjectHead94"><div><b>${rule.label||'المادة المرتبطة بالعمل'}</b><small>${multi?'يمكن اختيار أكثر من مادة عند التكامل بينها.':'اختر المادة الأقرب للعمل.'}</small></div>${selected.length?`<span>${selected.length} محدد</span>`:''}</div><div class="subjectGrid94">${list.map(btn).join('')}${general}</div></section>`}
function injectSubject(root){if(!shouldShowSubject())return;const h=$('.familyDetailsStep h1',root);if(!h)return;const card=h.closest('.card');if(card?.querySelector('.subjectBlock94'))return;const lead=$('.lead',card),duration=$('.durationContext',card);const host=duration||lead?.nextElementSibling;if(host)host.insertAdjacentHTML('beforebegin',subjectCard());else lead?.insertAdjacentHTML('afterend',subjectCard())}
function fixReasons(root){$$('.familyChoice',root).forEach(g=>{const q=clean($('small',g)?.textContent);if(!/سبب|ليش|لماذا/.test(q))return;$$('[data-family-pick]',g).forEach(b=>b.style.display='');$$('.v92More',g).forEach(x=>x.remove());g.classList.add('reasonsAll94')})}
function fixGoals(root){const h=$('h1',root);if(!h||clean(h.textContent)!=='الأهداف')return;const card=h.closest('.card')||root;if(card.dataset.goals94)return;card.dataset.goals94='1';$$('details',card).forEach(d=>{if(/أهداف إضافية/.test(clean(d.textContent)))d.remove()});$$('.v92More',card).forEach(x=>x.remove());const bs=$$('[data-goal]',card);if(!bs.length)return;const top=bs.slice(0,3),rest=bs.slice(3);bs.forEach((b,i)=>b.style.display=i<3?'':'none');if(rest.length){const grid=top[0]?.parentElement;const m=document.createElement('button');m.type='button';m.className='v94MoreGoals';m.textContent='عرض أهداف أخرى';m.onclick=()=>{const open=m.dataset.open==='1';rest.forEach(b=>b.style.display=open?'none':'');m.dataset.open=open?'0':'1';m.textContent=open?'عرض أهداف أخرى':'إخفاء الأهداف الإضافية'};grid?.insertAdjacentElement('afterend',m)}addSubjectGoals(card)}
function topic(){const r=raw();const pairs=[[/خط|كتابة/, 'الخط والكتابة'],[/قراء|فهم قرائي/,'القراءة والفهم القرائي'],[/كسور/,'الكسور'],[/جدول الضرب|الضرب/,'مهارات الضرب'],[/معادلات/,'المعادلات'],[/تجرب|مختبر/,'المهارات العملية والاستقصاء العلمي'],[/أمن|سلامة|إخلاء/,'الأمن والسلامة'],[/وطني|هوية/,'الهوية الوطنية'],[/سلوك|انضباط/,'السلوك والانضباط'],[/ذكاء اصطناعي/,'الذكاء الاصطناعي'],[/برمجة/,'البرمجة']];for(const[a,b]of pairs)if(a.test(r))return b;return clean(r).split(/[،,.]/)[0].replace(/^(نفذت|نفذنا|سويت|سوينا|عملت|عملنا|قدمت|قمنا)\s+/,'').slice(0,55)}
function target(){const g=gradeName(mem.get('grade')),s=stageName(mem.get('stage'));return g&&s?`طلاب الصف ${g} ${s==='متوسط'?'المتوسط':s==='ابتدائي'?'الابتدائي':'الثانوي'}`:'الطلاب'}
function addSubjectGoals(card){const subjects=selectedSubjects();if(!subjects.length)return;const grid=$('[data-goal]',card)?.parentElement;if(!grid)return;const subj=subjects[0],t=topic();const gs=[];if(/اللغة العربية|كفايات|دراسات لغوية/.test(subj)){if(/خط|كتابة/.test(t))gs.push(`تنمية مهارات الخط والكتابة لدى ${target()}`);else if(/قراءة/.test(t))gs.push(`رفع مستوى الطلاقة والفهم القرائي لدى ${target()}`)}else if(/رياضيات/.test(subj))gs.push(`رفع مستوى إتقان ${t||'المهارات الرياضية'} لدى ${target()}`);else if(/علوم|أحياء|كيمياء|فيزياء/.test(subj))gs.push(`تنمية الفهم والتطبيق العملي في ${t||subj} لدى ${target()}`);else if(/إنجليزية/.test(subj))gs.push(`تنمية مهارات اللغة الإنجليزية المرتبطة بـ${t||'موضوع العمل'} لدى ${target()}`);for(const g of gs){if($$('[data-goal]',card).some(b=>clean(b.dataset.goal)===clean(g)))continue;const b=document.createElement('button');b.type='button';b.className='chip v94SubjectGoal';b.dataset.goal=g;b.textContent=g;grid.insertBefore(b,grid.firstChild)}}
function titleCandidates(){const f=family(),sub=mem.get('subtype')||'',t=topic()||selectedSubjects()[0]||'',tar=target(),subject=selectedSubjects()[0]||'';let formal='',direct='',creative='';if(f==='برنامج / فعالية'){const kind=sub||'برنامج';formal=`${kind} ${/تحسين|تنمية|تعزيز/.test(t)?t:`تنمية ${t}`} لدى ${tar}`;direct=`${t} لدى ${tar}`;if(/خط|كتابة/.test(t))creative=kind==='مسابقة'?'أجمل خط':kind==='مبادرة'?'خطي أجمل':'خطي أجمل';else if(/قراءة/.test(t))creative=kind==='مسابقة'?'قارئ متميز':'أقرأ بطلاقة';else if(/ضرب/.test(t))creative=kind==='مسابقة'?'أبطال الضرب':'أتقن الضرب';else if(/كسور/.test(t))creative='أبطال الكسور';else if(/علوم|استقصاء|تجارب/.test(t)||/علوم|أحياء|كيمياء|فيزياء/.test(subject))creative=kind==='مسابقة'?'تحدي العالم الصغير':'مختبري الصغير';else creative=`${kind==='مبادرة'?'مبادرة ':''}${t}`}
 else if(f==='تحليل نتائج'){formal=`تحليل نتائج ${subject||'المادة'} لدى ${tar}`;direct=`تحليل أداء ${tar} في ${subject||t}`;creative=''}
 else if(f==='اجتماع / متابعة إدارية'){formal=`${sub||'اجتماع'} بشأن ${t||subject||'العمل المدرسي'}`;direct=`مراجعة ${t||subject||'العمل المستهدف'}`}
 else if(f==='تطوير مهني'){formal=`${sub||'برنامج تطوير مهني'} في ${t||subject||'الممارسات المهنية'}`;direct=`تطوير ممارسات ${subject||'التدريس'}`}
 else if(f==='خطة'){formal=`${sub||'خطة'} ${t||subject||'للتحسين'}`;direct=`خطة ${t||subject||'العمل المستهدف'}`}
 else {formal=`${sub||f} ${t}`;direct=t}
 return [...new Set([formal,direct,creative].map(clean).filter(x=>x.length>=8))].slice(0,3)}
function enhanceTitle(root){const h=$('h1',root);if(!h||clean(h.textContent)!=='عنوان الوثيقة')return;const card=h.closest('.card')||root;if(card.dataset.title94)return;card.dataset.title94='1';const candidates=titleCandidates();if(!candidates.length)return;const rec=$('.recommendedTitle',card);if(rec){const labels=['موصى به للتوثيق','مختصر وواضح','عنوان جاذب'];rec.outerHTML=`<div class="titleChoices94">${candidates.map((x,i)=>`<button class="titleChoice94 ${i===0?'primary94':''}" data-title-choice55="${x}"><small>${labels[i]||'اقتراح'}</small><b>${x}</b></button>`).join('')}</div>`}const actions=$('.titleActions',card);if(actions){const alt=$('[data-action="toggle-alt-titles"]',actions);if(alt)alt.remove()}const lead=$('.lead',card);if(lead)lead.textContent='اختر عنوانًا مناسبًا للتوثيق، أو استخدم عنوانًا مختصرًا أو جاذبًا عندما يناسب نوع العمل.'}
function capture(){document.addEventListener('input',e=>{if(e.target.id==='raw')mem.set('raw',e.target.value)} ,true);document.addEventListener('click',e=>{const t=e.target.closest('[data-type]');if(t)mem.set('family',t.dataset.type);const st=e.target.closest('[data-subtype]');if(st)mem.set('subtype',st.dataset.subtype);const sg=e.target.closest('[data-stage]');if(sg)mem.set('stage',sg.dataset.stage);const gr=e.target.closest('[data-grade]');if(gr)mem.set('grade',gr.dataset.grade);const sb=e.target.closest('[data-subject94]');if(sb){const block=sb.closest('.subjectBlock94'),multi=block?.dataset.subjectMulti==='1';let a=selectedSubjects(),v=sb.dataset.subject94;if(multi)a=a.includes(v)?a.filter(x=>x!==v):[...a,v];else a=[v];mem.set('subjects',a.join('|||'));mem.set('schoolGeneral','');block.querySelectorAll('[data-subject94]').forEach(x=>x.classList.toggle('on',a.includes(x.dataset.subject94)));const badge=$('.subjectHead94>span',block);if(badge)badge.textContent=`${a.length} محدد`;return}const ge=e.target.closest('[data-general94]');if(ge){mem.set('subjects','');mem.set('schoolGeneral','1');ge.closest('.subjectBlock94')?.querySelectorAll('[data-subject94]').forEach(x=>x.classList.remove('on'));ge.classList.add('on')}} ,true)}
function apply(root){injectSubject(root);fixReasons(root);fixGoals(root);enhanceTitle(root)}
export function installContext94(root=document){capture();const run=()=>requestAnimationFrame(()=>apply(root));new MutationObserver(run).observe(root,{childList:true,subtree:true});apply(root)}
