import {SUBJECTS94,ICONS94,SUBJECT_DECISION94} from './subject-registry94.js?v=94';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const clean=s=>String(s||'').replace(/\s+/g,' ').trim();
const mem={get(k){try{return sessionStorage.getItem('v94_'+k)||''}catch{return''}},set(k,v){try{sessionStorage.setItem('v94_'+k,String(v||''))}catch{}}};
const academic=/قراءة|قراءه|خط|كتابة|رياضيات|علوم|انجليزي|إنجليزي|عربي|لغتي|كسور|ضرب|جمع|طرح|معادلات|تجربة|مختبر|فيزياء|كيمياء|أحياء|رقمي|حاسب|اختبار|تحصيل|مهارة|مهارات|درس|منهج|صف/;
const general=/سلامة|امن|أمن|إخلاء|وطني|هوية|سلوك|انضباط|نشاط طلابي|توجيه|إرشاد|أسرة|مجتمع|بيئة|إعاقة/;
function gradeName(v){const x=clean(v);for(const n of ['الأول','الثاني','الثالث','الرابع','الخامس','السادس'])if(x.includes(n))return n;return''}
function family(){return mem.get('family')}
function raw(){return mem.get('raw')}
function subjectList(){const stage=mem.get('stage')||'متوسط',g=gradeName(mem.get('grade'))||'الأول';if(stage==='ثانوي'){const key=mem.get('track')||'الأولى المشتركة';return SUBJECTS94.ثانوي[key]||SUBJECTS94.ثانوي['الأولى المشتركة']}return SUBJECTS94[stage]?.[g]||SUBJECTS94.متوسط['الأول']}
function shouldShowSubject(){const f=family(),r=raw(),sub=mem.get('subtype'),rule=SUBJECT_DECISION94[f];if(!rule)return false;if(rule.when==='always')return true;if(f==='برنامج / فعالية')return academic.test(r)||!general.test(r);if(f==='خطة')return /علاج|إثراء|تحسين|تطوير/.test(sub)||academic.test(r);if(f==='تطوير مهني')return /تخصص|معلم|معلمين|تدريس/.test(r);return academic.test(r)}
function selectedSubjects(){return mem.get('subjects').split('|||').filter(Boolean)}
function subjectCard(){const rule=SUBJECT_DECISION94[family()]||{},selected=selectedSubjects(),list=subjectList(),multi=rule.multi!==false;const btn=x=>`<button type="button" class="subject94 ${selected.includes(x)?'on':''}" data-subject94="${x}"><span>${ICONS94[x]||'📘'}</span><b>${x}</b></button>`;const generalBtn=family()==='برنامج / فعالية'?`<button type="button" class="subject94 general94 ${mem.get('schoolGeneral')?'on':''}" data-general94="1"><span>🏫</span><b>عمل مدرسي عام</b></button>`:'';return `<section class="subjectBlock94" data-subject-multi="${multi?'1':'0'}"><div class="subjectHead94"><div><b>${rule.label||'المادة المرتبطة بالعمل'}</b><small>${multi?'يمكن اختيار أكثر من مادة عند التكامل بينها.':'اختر المادة الأقرب للعمل.'}</small></div>${selected.length?`<span>${selected.length} محدد</span>`:''}</div><div class="subjectGrid94">${list.map(btn).join('')}${generalBtn}</div></section>`}
function injectSubject(root){if(!shouldShowSubject())return;const h=$('.familyDetailsStep h1',root);if(!h)return;const card=h.closest('.card');if(card?.querySelector('.subjectBlock94'))return;const lead=$('.lead',card),duration=$('.durationContext',card);const host=duration||lead?.nextElementSibling;if(host)host.insertAdjacentHTML('beforebegin',subjectCard());else lead?.insertAdjacentHTML('afterend',subjectCard())}
function showAllReasons(root){$$('.familyChoice',root).forEach(g=>{const q=clean($('small',g)?.textContent);if(!/سبب|ليش|لماذا/.test(q))return;$$('[data-family-pick]',g).forEach(b=>{b.style.display='';b.hidden=false});$$('.v92More',g).forEach(x=>x.remove());$$('.v92Tag',g).forEach(x=>x.remove())})}
function capture(){document.addEventListener('input',e=>{if(e.target.id==='raw')mem.set('raw',e.target.value)},true);document.addEventListener('click',e=>{const t=e.target.closest('[data-type]');if(t)mem.set('family',t.dataset.type);const st=e.target.closest('[data-subtype]');if(st)mem.set('subtype',st.dataset.subtype);const sg=e.target.closest('[data-stage]');if(sg)mem.set('stage',sg.dataset.stage);const gr=e.target.closest('[data-grade]');if(gr)mem.set('grade',gr.dataset.grade);const sb=e.target.closest('[data-subject94]');if(sb){const block=sb.closest('.subjectBlock94'),multi=block?.dataset.subjectMulti==='1';let a=selectedSubjects(),v=sb.dataset.subject94;if(multi)a=a.includes(v)?a.filter(x=>x!==v):[...a,v];else a=[v];mem.set('subjects',a.join('|||'));mem.set('schoolGeneral','');block.querySelectorAll('[data-subject94]').forEach(x=>x.classList.toggle('on',a.includes(x.dataset.subject94)));const badge=$('.subjectHead94>span',block);if(badge)badge.textContent=`${a.length} محدد`;return}const ge=e.target.closest('[data-general94]');if(ge){mem.set('subjects','');mem.set('schoolGeneral','1');ge.closest('.subjectBlock94')?.querySelectorAll('[data-subject94]').forEach(x=>x.classList.remove('on'));ge.classList.add('on')}} ,true)}
function apply(root){injectSubject(root);showAllReasons(root)}
export function installContext94(root=document){capture();const run=()=>requestAnimationFrame(()=>apply(root));new MutationObserver(run).observe(root,{childList:true,subtree:true});apply(root)}
