import {joinAr} from './engine80.js?v=80';
import {displayAudiences} from './output-quality-v5.js';
import {guideSupportSentence76,strongGuideLinks76} from './guide-link76.js?v=80';
import {bestTitle108} from './title108.js?v=110';
const c=s=>String(s||'').replace(/\|{2,}/g,'، ').replace(/\s*،\s*/g,'، ').replace(/\s+/g,' ').trim();
const d=(fd,k)=>c(fd?.[k]||'');
const ctx=s=>({a:joinAr(displayAudiences(s))||'الفئة المستفيدة',t:s.classification?.type||'',title:bestTitle108(s),fd:s.metadata?.familyDetails||{}});
const sentence=(label,value)=>value?`${label}${value}.`:'';
function placePhrase(s){const m=s.metadata||{},mode=m.placeMode||'',place=c(m.place||m.placeChoice||'');if(!mode&&!place)return'';if(mode==='عن بُعد')return place&&place!=='عن بُعد'?` عن بُعد باستخدام ${place}`:' عن بُعد';if(mode==='خارج المدرسة'){const x=place.replace(/^خارج المدرسة\s*-?\s*/,'').trim();return x?` خارج المدرسة في ${x}`:' خارج المدرسة';}if(mode==='داخل المدرسة')return place&&place!=='داخل المدرسة'?` في ${place}`:' داخل المدرسة';return place?` في ${place}`:''}
function durationPhrase(s){const v=c(s.metadata?.duration||s.metadata?.durationChoice||'');if(!v)return'';if(v==='مستمر')return' بصورة مستمرة';if(v==='فصل دراسي')return' على مدى فصل دراسي';if(/حصة|حصتان|حصص/.test(v))return` خلال ${v}`;if(/يوم|أيام|يومان|أسبوع|أسابيع|أسبوعان/.test(v))return` على مدى ${v}`;return` خلال ${v}`}
function contextTail(s){return`${placePhrase(s)}${durationPhrase(s)}`}
function focusSentence(f){const x=d(f,'skillFocus');return x?`وركز العمل على ${x}.`:''}
function reasonSentence(v){v=c(v);if(!v)return'';if(/^معالجة /.test(v))return`وجاء التنفيذ لمعالجة ${v.replace(/^معالجة /,'')}.`;if(/^تنمية /.test(v))return`وجاء التنفيذ بهدف ${v}.`;if(/^دعم /.test(v))return`وجاء التنفيذ لدعم ${v.replace(/^دعم /,'')}.`;if(/^تعزيز /.test(v))return`وجاء التنفيذ بهدف ${v}.`;if(/^رفع /.test(v))return`وجاء التنفيذ بهدف ${v}.`;if(/^إثراء /.test(v))return`وجاء التنفيذ بهدف ${v}.`;if(/^تفعيل /.test(v))return`وجاء التنفيذ لتفعيل ${v.replace(/^تفعيل /,'')}.`;return`وجاء العمل استجابةً إلى ${v}.`}
function measurement(f){const x=d(f,'measurement');if(!x)return'';if(x.includes('لم يتم القياس بعد'))return'ولم يتم قياس الأثر بعد.';return`وتم التحقق من النتيجة من خلال ${x}.`}
function addCommonLong(a,f){const m=measurement(f);if(m)a.push(m)}
function core(s,level='medium'){const x=ctx(s),f=x.fd,a=[],tail=contextTail(s),focus=focusSentence(f);if(x.t==='برنامج / فعالية'){a.push(`نُفذ ${x.title} للفئة ${x.a}${tail}.`);if(focus)a.push(focus);const r=reasonSentence(d(f,'reason'));if(r)a.push(r);if(d(f,'goal'))a.push(sentence('واستهدف العمل ',d(f,'goal')));if(d(f,'method'))a.push(sentence('وتضمن التنفيذ ',d(f,'method')));if(level!=='short'&&d(f,'participation'))a.push(sentence('ولوحظ أثناء التنفيذ ',d(f,'participation')));if(level==='long')addCommonLong(a,f)}
else if(x.t==='اجتماع / متابعة إدارية'){a.push(`عُقد ${x.title} بمشاركة ${x.a}${tail}.`);if(focus)a.push(focus);if(d(f,'purpose'))a.push(sentence('وكان الغرض الرئيس ',d(f,'purpose')));if(d(f,'work'))a.push(sentence('ونوقش خلال الاجتماع ',d(f,'work')));if(level!=='short'&&d(f,'product'))a.push(sentence('وانتهى الاجتماع إلى ',d(f,'product')));if(d(f,'owner'))a.push(sentence('وأسند التنفيذ أو المتابعة إلى ',d(f,'owner')));if(level==='long'&&d(f,'follow'))a.push(sentence('واتُّفق على متابعة القرارات من خلال ',d(f,'follow')))}
else if(x.t==='تحليل نتائج'){a.push(`أُجري ${x.title} للفئة ${x.a}${durationPhrase(s)}.`);if(focus)a.push(focus);if(d(f,'basis'))a.push(sentence('واستند التحليل إلى ',d(f,'basis')));if(d(f,'finding'))a.push(sentence('وأظهرت النتائج ',d(f,'finding')));if(level!=='short'&&d(f,'cause'))a.push(sentence('وكان التفسير الأقرب المختار ',d(f,'cause')));if(d(f,'action'))a.push(sentence('وبناءً على التحليل اتُّخذ إجراء شمل ',d(f,'action')));if(d(f,'follow'))a.push(sentence('وستتم متابعة التقدم من خلال ',d(f,'follow')));if(level==='long')addCommonLong(a,f)}
else if(x.t==='خطة'){a.push(`أُعدت ${x.title} للفئة ${x.a}${durationPhrase(s)}.`);if(focus)a.push(focus);if(d(f,'basis'))a.push(sentence('وبُنيت الخطة على ',d(f,'basis')));if(d(f,'goal'))a.push(sentence('وتهدف الخطة إلى ',d(f,'goal')));if(d(f,'method'))a.push(sentence('وتتضمن إجراءات التنفيذ ',d(f,'method')));if(d(f,'owner'))a.push(sentence('ويتولى التنفيذ أو المتابعة ',d(f,'owner')));if(d(f,'follow'))a.push(sentence('وتتم متابعة الخطة من خلال ',d(f,'follow')));if(level==='long')addCommonLong(a,f)}
else if(x.t==='إجراء متابعة'){a.push(`نُفذت ${x.title} للفئة ${x.a}${durationPhrase(s)}.`);if(focus)a.push(focus);const goal=d(f,'goal')||d(f,'reason')||d(f,'purpose'),method=d(f,'method')||d(f,'tool')||d(f,'basis'),action=d(f,'action')||d(f,'outcome')||d(f,'product');if(goal)a.push(sentence('وتركزت المتابعة على ',goal));if(method)a.push(sentence('واعتمدت المتابعة على ',method));if(level!=='short'&&action)a.push(sentence('ونتج عن المتابعة إجراء شمل ',action));if(d(f,'follow'))a.push(sentence('والخطوة التالية هي ',d(f,'follow')));if(level==='long')addCommonLong(a,f)}
else if(x.t==='تطوير مهني'){a.push(`نُفذ ${x.title} للفئة ${x.a}${tail}.`);if(focus)a.push(focus);const need=d(f,'need')||d(f,'reason')||d(f,'basis'),method=d(f,'method')||d(f,'content'),application=d(f,'application')||d(f,'product')||d(f,'impact');if(need)a.push(sentence('وجاء النشاط لمعالجة احتياج مهني يتمثل في ',need));if(method)a.push(sentence('وتضمن التنفيذ ',method));if(level!=='short'&&application){if(application.includes('لم يبدأ التطبيق بعد'))a.push('ولم يبدأ التطبيق العملي بعد.');else a.push(sentence('وتمثل التطبيق العملي في ',application))}if(d(f,'follow'))a.push(sentence('وستتم متابعة التطبيق من خلال ',d(f,'follow')));if(level==='long')addCommonLong(a,f)}
else if(x.t==='شراكة مجتمعية'){a.push(`نُفذت ${x.title}${tail}.`);const r=reasonSentence(d(f,'reason'));if(r)a.push(r);if(d(f,'method'))a.push(sentence('وتم تنفيذ الشراكة من خلال ',d(f,'method')));if(level!=='short'&&d(f,'participation'))a.push(sentence('ولوحظ أثناء التنفيذ ',d(f,'participation')));if(level==='long')addCommonLong(a,f)}
else if(x.t==='صيانة وتجهيزات'){a.push(`تم توثيق ${x.title}${tail}.`);if(d(f,'reason'))a.push(sentence('وتمثل الاحتياج في ',d(f,'reason')));if(d(f,'method'))a.push(sentence('وشمل الإجراء ',d(f,'method')));if(d(f,'status'))a.push(sentence('وحالة الإجراء الحالية: ',d(f,'status')));if(d(f,'follow'))a.push(sentence('وستتم المتابعة من خلال ',d(f,'follow')))}
else{a.push(`تم توثيق ${x.title}${tail}.`);if(focus)a.push(focus);const r=reasonSentence(d(f,'reason'));if(r)a.push(r);if(d(f,'method'))a.push(sentence('وتضمن التنفيذ ',d(f,'method')));if(level!=='short'&&d(f,'participation'))a.push(sentence('ولوحظ أثناء التنفيذ ',d(f,'participation')));if(d(f,'status'))a.push(sentence('وحالة الإجراء الحالية: ',d(f,'status')))}return c(a.join(' '))}
export function shortText80(s){return core(s,'short')}
export function mediumText80(s){const g=guideSupportSentence76(s,1);return c(`${core(s,'medium')}${g?` ${g}`:''}`)}
export function longText80(s){const g=guideSupportSentence76(s,2);return c(`${core(s,'long')}${g?` ${g}`:''}`)}
const LABELS={skillFocus:'المهارة/الجانب المستهدف: ',reason:'سبب التنفيذ: ',goal:'الهدف: ',method:'طريقة التنفيذ: ',participation:'ملاحظة أثناء التنفيذ: ',purpose:'غرض الاجتماع: ',work:'أبرز ما نوقش: ',product:'القرار أو المخرج: ',basis:'أساس العمل: ',finding:'أبرز ما ظهر: ',cause:'التفسير الأقرب: ',action:'الإجراء: ',follow:'المتابعة: ',need:'الاحتياج المهني: ',application:'التطبيق: ',measurement:'القياس: ',owner:'المسؤول: ',status:'حالة الإجراء: '};
function bulletIntro(s,x){if(x.t==='اجتماع / متابعة إدارية')return`عُقد ${x.title}.`;if(x.t==='تحليل نتائج')return`أُجري ${x.title}.`;if(x.t==='خطة')return`أُعدت ${x.title}.`;if(x.t==='إجراء متابعة')return`نُفذت ${x.title}.`;if(x.t==='تطوير مهني')return`نُفذ ${x.title}.`;if(x.t==='شراكة مجتمعية')return`نُفذت ${x.title}.`;if(x.t==='صيانة وتجهيزات')return`تم توثيق ${x.title}.`;return`نُفذ ${x.title}.`}
export function bulletText80(s){const x=ctx(s),a=[bulletIntro(s,x)],place=c(s.metadata?.place||s.metadata?.placeChoice||''),duration=c(s.metadata?.duration||s.metadata?.durationChoice||'');if(place)a.push(`مكان التنفيذ: ${place}.`);if(duration)a.push(`المدة: ${duration}.`);for(const [k,v] of Object.entries(x.fd).filter(([,v])=>c(v)).slice(0,7)){if(k==='application'&&c(v).includes('لم يبدأ التطبيق بعد'))a.push('التطبيق: لم يبدأ التطبيق بعد.');else a.push(`${LABELS[k]||'تفصيل: '}${c(v)}.`)}strongGuideLinks76(s).slice(0,2).forEach(z=>a.push(`يدعم العمل الممارسة المرتبطة ب${String(z.text||'').replace(/\.$/,'')} ضمن مجال ${z.domainName}.`));return a.slice(0,9)}
