import {joinAr} from './engine.js';
import {displayAudiences,selectedGoals,smartTitle,executionDescription} from './output-quality-v5.js';
import {guideSupportSentence73,strongGuideLinks73} from './guide-link73.js?v=73';
const c=s=>String(s||'').replace(/\s+/g,' ').trim();
const ctx=s=>({a:joinAr(displayAudiences(s))||'الفئة المستفيدة',g:selectedGoals(s),p:s.metadata.place||'',d:s.metadata.duration||'',t:s.classification.type,topic:s.topic||'موضوع العمل',title:smartTitle(s)});
export function shortText73(s){const x=executionDescription(s).split(/[.؟!]/).map(c).filter(Boolean);return c(x.slice(0,2).join('. ')+(x.length?'.':''))}
export function mediumText73(s){const x=ctx(s),g=x.g.slice(0,2),guide=guideSupportSentence73(s,1);return c(`${executionDescription(s)}${g.length?` وجرى توجيه التنفيذ بما ينسجم مع ${joinAr(g)}.`:''}${guide?` ${guide}`:''}`)}
export function longText73(s){const x=ctx(s),w=[x.p?`في ${x.p}`:'',x.d?`خلال ${x.d}`:''].filter(Boolean).join('، '),guide=guideSupportSentence73(s,2);let body='';if(x.t==='تحليل نتائج')body=`تم تنفيذ ${x.title}${w?` ${w}`:''} للفئة ${x.a}. بدأ العمل بجمع النتائج وتنظيمها ثم تصنيف مستويات الأداء ورصد جوانب القوة والجوانب التي تحتاج إلى تحسين. وتمت قراءة البيانات لتحديد الاحتياجات الأكثر أولوية والفئات التي قد تحتاج إلى دعم أو إثراء.`;else if(x.t==='اجتماع / متابعة إدارية')body=`عُقد ${x.title}${w?` ${w}`:''} بمشاركة ${x.a}. استُعرض موضوع الاجتماع ومحاوره، ثم نوقشت الأولويات والتحديات والمسؤوليات والإجراءات الممكنة، مع توثيق القرارات والتكليفات المتفق عليها.`;else if(x.t==='خطة')body=`أُعدت ${x.title}${w?` ${w}`:''} لمعالجة ${x.topic} وخدمة ${x.a}. بُنيت الخطة على تحديد الأولويات والأهداف ثم تنظيم الإجراءات والمسؤوليات ومؤشرات الإنجاز بما يجعل التنفيذ واضحًا وقابلًا للتوثيق والقياس.`;else if(x.t==='تطوير مهني')body=`تمت الاستفادة من ${x.title}${w?` ${w}`:''} في دعم النمو المهني المرتبط بـ${x.topic}. وركزت التجربة على ربط المعرفة بالممارسة وتحديد التطبيقات الممكنة في بيئة العمل، مع توثيق المشاركة بالشهادة أو إثبات الجهة والمدة عند توفرها.`;else body=`نُفذ ${x.title}${w?` ${w}`:''} لصالح ${x.a}. اشتمل التنفيذ على أنشطة وممارسات مرتبطة بموضوع العمل وطبيعة الفئة المستفيدة، مع تنظيم الخطوات بما يحقق وضوح الهدف وسهولة المشاركة ويخدم الأهداف المحددة للعمل.`;return c(`${body}${guide?` ${guide}`:''}`)}
export function bulletText73(s){const x=ctx(s),a=[`تنفيذ ${x.title} لصالح ${x.a}.`];if(x.p)a.push(`مكان التنفيذ: ${x.p}.`);if(x.d)a.push(`المدة: ${x.d}.`);x.g.slice(0,3).forEach(g=>a.push(`الهدف: ${g}.`));const links=strongGuideLinks73(s);links.slice(0,2).forEach(z=>a.push(`الارتباط بالدليل: مجال ${z.domainName} — ${z.standard} — المؤشر (${z.code})؛ دعم للممارسات المرتبطة به دون الجزم بتحقق المؤشر.`));return a.slice(0,8)}
