import {esc} from './engine.js';
import {evidenceItems} from './output-quality.js';
export function selectedEvidence(state){const items=[...(state.answers?.evidence||[])];const other=String(state.metadata?.otherEvidence||'').trim();return other?[...items,other]:items}
function iconFor(f){const t=f.type||'',n=(f.name||'').toLowerCase();if(t.startsWith('image/'))return'🖼️';if(t==='application/pdf'||n.endsWith('.pdf'))return'📕';if(/word|document/.test(t)||/\.docx?$/.test(n))return'📘';if(/sheet|excel/.test(t)||/\.xlsx?$/.test(n))return'📗';if(/presentation|powerpoint/.test(t)||/\.pptx?$/.test(n))return'📙';return'📎'}
function size(v){if(!v)return'';if(v<1024)return`${v} B`;if(v<1048576)return`${(v/1024).toFixed(1)} KB`;return`${(v/1048576).toFixed(1)} MB`}
function imageThumbs(files){const imgs=files.map((f,i)=>({f,i})).filter(x=>(x.f.type||'').startsWith('image/'));if(!imgs.length)return'';return `<div class="thumbSection"><div class="sectionTitleRow"><b>الصور المرفقة</b><small>${imgs.length} صورة</small></div><div class="thumbGrid">${imgs.map(({f,i})=>{let src='';try{src=URL.createObjectURL(f.file||f)}catch{}return `<div class="thumbCard">${src?`<img src="${src}" alt="${esc(f.name||'صورة')}">`:'<div class="thumbFallback">🖼️</div>'}<button class="thumbRemove" data-remove-attachment="${i}" aria-label="حذف الصورة">×</button><div class="thumbName">${esc(f.name||'صورة')}</div></div>`}).join('')}</div></div>`}
export function evidencePage(state){const suggestions=evidenceItems(state),selected=state.answers?.evidence||[],otherOn=Boolean(state.metadata?.otherEvidenceEnabled),files=state.attachments||[],chosen=selectedEvidence(state);const advice=!chosen.length&&!files.length&&!state.metadata?.evidenceLink?'<div class="warn compact">لم تضف شاهدًا أو مرفقًا بعد. يمكنك المتابعة، لكن الوثيقة ستكون دون مرفقات داعمة.</div>':'<div class="helperBox"><b>المرفقات محفوظة مع المسودة</b><p>يمكنك الرجوع لاحقًا لإضافة مرفقات أو حذفها.</p></div>';
const nonImages=files.map((f,i)=>({f,i})).filter(x=>!(x.f.type||'').startsWith('image/'));
return `<section class="card evidenceStep"><button class="linkBtn" data-action="edit-description">→ رجوع</button><div class="stepBadge">الخطوة الرابعة</div><h1>الشواهد والمرفقات</h1><p class="lead">اختر الشواهد المتوفرة، ثم أضف الصور أو الملفات أو الرابط الداعم.</p><div class="chips choiceGrid">${suggestions.map(x=>`<button class="chip ${selected.includes(x)?'on':''}" data-evidence="${esc(x)}">${esc(x)}</button>`).join('')}<button class="chip ${otherOn?'on':''}" data-action="toggle-other-evidence">شاهد آخر</button></div>${otherOn?`<label class="fullField"><span>اكتب اسم الشاهد</span><input id="otherEvidence" value="${esc(state.metadata?.otherEvidence||'')}" placeholder="مثال: خطاب مشاركة أو بطاقة ملاحظة"></label>`:''}${advice}<div class="uploadPanel"><label class="uploadPrimary"><span class="uploadPrimaryIcon">＋</span><span><b>إرفاق صور أو ملفات</b><small>من الاستوديو أو تطبيق الملفات</small></span><input id="evidenceFiles" type="file" accept="image/*,.pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx,.txt,.csv" multiple hidden></label><label class="fullField linkField"><span>أو أضف رابط شاهد</span><input id="evidenceLink" inputmode="url" value="${esc(state.metadata?.evidenceLink||'')}" placeholder="https://..."></label></div>${imageThumbs(files)}${nonImages.length?`<div class="fileList"><b>الملفات المرفقة</b>${nonImages.map(({f,i})=>`<div class="fileRow"><span>${iconFor(f)} <span>${esc(f.name)}</span> <small>${size(f.size)}</small></span><button class="linkBtn dangerText" data-remove-attachment="${i}">حذف</button></div>`).join('')}</div>`:''}<div class="row"><button class="btn primary" data-action="finalize">حفظ ومعاينة الوثيقة</button><button class="btn" data-action="finalize">المتابعة بدون مرفقات إضافية</button></div></section>`}
