import {esc} from './engine85.js?v=85';
import {evidenceItems} from './output-quality.js';
import {evidenceReferenceSummary112} from './evidence-reference112.js?v=112';
const uniq=a=>[...new Set((a||[]).filter(Boolean))];
export function selectedEvidence(state){const items=[...(state.answers?.evidence||[])];const other=String(state.metadata?.otherEvidence||'').trim();return other?[...items,other]:items}
function iconFor(f){const t=f.type||'',n=(f.name||'').toLowerCase();if(t.startsWith('image/'))return'صورة';if(t==='application/pdf'||n.endsWith('.pdf'))return'PDF';if(/word|document/.test(t)||/\.docx?$/.test(n))return'Word';if(/sheet|excel/.test(t)||/\.xlsx?$/.test(n))return'Excel';if(/presentation|powerpoint/.test(t)||/\.pptx?$/.test(n))return'PowerPoint';return'ملف'}
function size(v){if(!v)return'';if(v<1024)return`${v} B`;if(v<1048576)return`${(v/1024).toFixed(1)} KB`;return`${(v/1048576).toFixed(1)} MB`}
function imageThumbs(files){const imgs=files.map((f,i)=>({f,i})).filter(x=>(x.f.type||'').startsWith('image/'));if(!imgs.length)return'';return `<div class="thumbSection"><div class="sectionTitleRow"><b>الصور المرفقة</b><small>${imgs.length} صورة</small></div><div class="thumbGrid">${imgs.map(({f,i})=>{let src='';try{src=URL.createObjectURL(f.file||f)}catch{}return `<div class="thumbCard">${src?`<img src="${src}" alt="${esc(f.name||'صورة')}">`:'<div class="thumbFallback">صورة</div>'}<button class="thumbRemove" data-remove-attachment="${i}" aria-label="حذف الصورة">×</button><div class="thumbName">${esc(f.name||'صورة')}</div></div>`}).join('')}</div></div>`}
function currentEvidence112(state,files){const chosen=selectedEvidence(state),link=String(state.metadata?.evidenceLink||'').trim(),parts=[];if(chosen.length)parts.push(...chosen.map(x=>`<span class="evidenceHaveTag112">✓ ${esc(x)}</span>`));if(files.length)parts.push(`<span class="evidenceHaveTag112">✓ ${files.length} ${files.length===1?'مرفق':'مرفقات'}</span>`);if(link)parts.push('<span class="evidenceHaveTag112">✓ رابط شاهد</span>');return parts.length?`<div class="evidenceHave112">${parts.join('')}</div>`:'<p class="questionHelp">لم تحدد أو ترفق شاهدًا بعد.</p>'}
function sourceGuidance112(state){const ref=evidenceReferenceSummary112(state);if(!ref.hasSuggestions)return'';const items=ref.suggestions.slice(0,4);return `<section class="evidenceIntelligence112"><div class="sectionTitleRow"><div><b>ما الذي يقوّي ملف التوثيق؟</b><small>اقتراحات مرتبطة بطبيعة هذا العمل</small></div><span class="evidenceSourceBadge112">مرجع: جدول حصر الشواهد</span></div><div class="evidenceTargetGrid112">${items.map((x,i)=>`<article class="evidenceTarget112 ${i===0?'recommended112':''}"><div class="evidenceTargetTop112"><span>${i===0?'الأقرب للعمل':'اقتراح داعم'}</span><small>${esc(x.domain)}</small></div><p>${esc(x.text)}</p><div>${(x.tags||[]).slice(0,3).map(t=>`<span>${esc(t)}</span>`).join('')}</div></article>`).join('')}</div><p class="evidenceDisclaimer112">هذه اقتراحات لتنظيم وتقوية ملف الشواهد، وليست حكمًا رسميًا بتحقق مؤشر. أرفق فقط ما نُفذ أو توفر فعليًا.</p></section>`}
export function evidencePage(state){const contextual=state.metadata?.contextEvidence85||[],suggestions=uniq([...contextual,...evidenceItems(state)]),selected=state.answers?.evidence||[],otherOn=Boolean(state.metadata?.otherEvidenceEnabled),files=state.attachments||[],chosen=selectedEvidence(state);const advice=!chosen.length&&!files.length&&!state.metadata?.evidenceLink?'<div class="warn compact">لم تضف شاهدًا أو مرفقًا بعد. يمكنك المتابعة، لكن الوثيقة ستكون دون مرفقات داعمة.</div>':'<div class="helperBox"><b>الشواهد جزء من العمل الموثق</b><p>يعرض النظام ما لديك أولًا، ثم الشواهد المناسبة للعائلة، ثم اقتراحات مرجعية تقوّي ملف التوثيق.</p></div>';const nonImages=files.map((f,i)=>({f,i})).filter(x=>!(x.f.type||'').startsWith('image/'));return `<section class="card evidenceStep"><button class="linkBtn" data-action="edit-description">→ رجوع</button><div class="stepBadge">الشواهد</div><h1>الشواهد والمرفقات</h1><p class="lead">أضف ما يثبت العمل فعلًا. لن يعتبر النظام مجرد اختيار شاهد دليلًا على تحقق مؤشر رسمي.</p><section class="evidenceCurrent112"><div class="sectionTitleRow"><div><b>الشواهد الموجودة الآن</b><small>ما اخترته أو أرفقته في هذه الوثيقة</small></div></div>${currentEvidence112(state,files)}</section><section class="evidenceSuggested112"><div class="sectionTitleRow"><div><b>الشواهد المناسبة لهذا العمل</b><small>اختر فقط ما لديك فعلًا</small></div></div><div class="chips choiceGrid">${suggestions.map(x=>`<button class="chip ${selected.includes(x)?'on':''}" data-evidence="${esc(x)}">${esc(x)}</button>`).join('')}<button class="chip ${otherOn?'on':''}" data-action="toggle-other-evidence">شاهد آخر</button></div>${otherOn?`<label class="fullField"><span>اكتب اسم الشاهد</span><input id="otherEvidence" value="${esc(state.metadata?.otherEvidence||'')}"></label>`:''}</section>${sourceGuidance112(state)}${advice}<div class="uploadPanel"><label class="uploadPrimary"><span class="uploadPrimaryIcon">＋</span><span><b>إرفاق صور أو ملفات</b><small>من الاستوديو أو تطبيق الملفات</small></span><input id="evidenceFiles" type="file" accept="image/*,.pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx,.txt,.csv" multiple hidden></label><label class="fullField linkField"><span>أو أضف رابط شاهد</span><input id="evidenceLink" inputmode="url" value="${esc(state.metadata?.evidenceLink||'')}" placeholder="https://..."></label></div>${imageThumbs(files)}${nonImages.length?`<div class="fileList"><b>الملفات المرفقة</b>${nonImages.map(({f,i})=>`<div class="fileRow"><span><b>${iconFor(f)}</b> <span>${esc(f.name)}</span> <small>${size(f.size)}</small></span><button class="linkBtn dangerText" data-remove-attachment="${i}">حذف</button></div>`).join('')}</div>`:''}<div class="row"><button class="btn primary" data-action="finalize">حفظ ومعاينة الوثيقة</button><button class="btn" data-action="finalize">المتابعة بدون مرفقات إضافية</button></div></section>`}
