import {esc} from './engine85.js?v=85';
import {evidenceItems} from './output-quality.js';
import {evidenceReferenceSummary112} from './evidence-reference112.js?v=112';
const uniq=a=>[...new Set((a||[]).filter(Boolean))];
export function selectedEvidence(state){const items=[...(state.answers?.evidence||[])];const other=String(state.metadata?.otherEvidence||'').trim();return other?[...items,other]:items}
function iconFor(f){const t=f.type||'',n=(f.name||'').toLowerCase();if(t.startsWith('image/'))return'صورة';if(t==='application/pdf'||n.endsWith('.pdf'))return'PDF';if(/word|document/.test(t)||/\.docx?$/.test(n))return'Word';if(/sheet|excel/.test(t)||/\.xlsx?$/.test(n))return'Excel';if(/presentation|powerpoint/.test(t)||/\.pptx?$/.test(n))return'PowerPoint';return'ملف'}
function size(v){if(!v)return'';if(v<1024)return`${v} B`;if(v<1048576)return`${(v/1024).toFixed(1)} KB`;return`${(v/1048576).toFixed(1)} MB`}
function imageThumbs(files){const imgs=files.map((f,i)=>({f,i})).filter(x=>(x.f.type||'').startsWith('image/'));if(!imgs.length)return'';return `<div class="thumbSection"><div class="sectionTitleRow"><b>الصور المرفقة</b><small>${imgs.length} صورة</small></div><div class="thumbGrid">${imgs.map(({f,i})=>{let src='';try{src=URL.createObjectURL(f.file||f)}catch{}return `<div class="thumbCard">${src?`<img src="${src}" alt="${esc(f.name||'صورة')}">`:'<div class="thumbFallback">صورة</div>'}<button class="thumbRemove" data-remove-attachment="${i}" aria-label="حذف الصورة">×</button><div class="thumbName">${esc(f.name||'صورة')}</div></div>`}).join('')}</div></div>`}
function currentEvidence112(state,files){const chosen=selectedEvidence(state),link=String(state.metadata?.evidenceLink||'').trim(),parts=[];if(chosen.length)parts.push(...chosen.map(x=>`<span class="evidenceHaveTag112">✓ ${esc(x)}</span>`));if(files.length)parts.push(`<span class="evidenceHaveTag112">✓ ${files.length} ${files.length===1?'مرفق':'مرفقات'}</span>`);if(link)parts.push('<span class="evidenceHaveTag112">✓ رابط شاهد</span>');return parts.length?`<div class="evidenceHave112">${parts.join('')}</div>`:'<p class="questionHelp">لم تحدد أو ترفق شاهدًا بعد.</p>'}
function analysisEvidenceChain112(state){if(state?.classification?.type!=='تحليل نتائج')return'';const fd=state?.metadata?.familyDetails||{},hasAction=Boolean(String(fd.action||'').trim()),hasFollow=Boolean(String(fd.follow||'').trim());const chain=[
 {n:'91',title:'تحليل نتائج المتعلمين',detail:'الوثيقة الحالية هي الشاهد الأساسي: نتائج فعلية + قراءة كمية واضحة.',status:'current'},
 {n:'92',title:'تصنيف المتعلمين وفق النتائج',detail:'أظهر توزيع الطلاب إلى مستويات أو فئات مبنية على الدرجات نفسها.',status:'current'},
 {n:'93',title:'فجوة الأداء وأسبابها',detail:'اربط الضعف أو التفاوت بتفسير مدعوم بالبيانات أو الملاحظة، دون افتراض سبب غير مثبت.',status:fd.finding?'current':'needed'},
 {n:'94',title:'خطة علاجية وفق التصنيف',detail:'إذا ظهرت فئة تحتاج تدخلًا، أنشئ لها خطة علاجية مستقلة مرتبطة بهذا التحليل.',status:hasAction?'linked':'next'},
 {n:'95',title:'خطة إثرائية وفق التصنيف',detail:'إذا ظهرت فئة متقدمة، أنشئ لها خطة إثرائية مستقلة بدل الاكتفاء بذكرها داخل التقرير.',status:'next'},
 {n:'96',title:'التغذية الراجعة المقدمة للمتعلمين',detail:'وثّق التغذية الراجعة التي قُدمت للطلاب بناءً على النتائج، واربطها بالفئة أو الحاجة الظاهرة.',status:hasAction?'linked':'next'},
 {n:'97',title:'خطط الفاقد التعليمي لجميع المواد',detail:'تُضاف عند ثبوت وجود فاقد تعليمي؛ لا يفترض النظام وجوده من الدرجات الكلية وحدها.',status:'next'},
 {n:'98',title:'متابعة مستوى التقدم',detail:'بعد التدخل أعد القياس ووثّق التقدم الفعلي؛ خطة القياس وحدها ليست نتيجة مقاسة.',status:hasFollow?'linked':'next'}
 ];return `<section class="analysisEvidenceChain117"><div class="sectionTitleRow"><div><b>سلسلة توثيق تحليل النتائج</b><small>ترتيب عملي مستخرج من بنود جدول حصر الشواهد ذات الصلة بتحليل النتائج</small></div><span class="evidenceSourceBadge112">مرجع: جدول حصر الشواهد</span></div><div class="evidenceChainGrid117">${chain.map(x=>`<article class="evidenceChainItem117 ${x.status}"><span class="evidenceChainNo117">${x.n}</span><div><b>${esc(x.title)}</b><p>${esc(x.detail)}</p></div><small>${x.status==='current'?'يدعم الوثيقة الحالية':x.status==='linked'?'مرتبط بما أدخلته':'خطوة لاحقة عند انطباقها'}</small></article>`).join('')}</div><div class="evidenceChainRule117"><b>قاعدة جودة</b><span>لا يعتبر وجود خطة علاجية أو إثرائية أثرًا بحد ذاته. الأثر يوثق عند وجود متابعة أو إعادة قياس فعلية.</span></div></section>`}
function sourceGuidance112(state){const ref=evidenceReferenceSummary112(state);if(!ref.hasSuggestions)return'';const items=ref.suggestions.slice(0,4);return `${analysisEvidenceChain112(state)}<section class="evidenceIntelligence112"><div class="sectionTitleRow"><div><b>شواهد مرجعية إضافية</b><small>اقتراحات مرتبطة بطبيعة هذا العمل وليست قائمة إلزامية</small></div><span class="evidenceSourceBadge112">مرجع: جدول حصر الشواهد</span></div><div class="evidenceTargetGrid112">${items.map((x,i)=>`<article class="evidenceTarget112 ${i===0?'recommended112':''}"><div class="evidenceTargetTop112"><span>${i===0?'الأقرب للعمل':'اقتراح داعم'}</span><small>${esc(x.domain)}</small></div><p>${esc(x.text)}</p><div>${(x.tags||[]).slice(0,3).map(t=>`<span>${esc(t)}</span>`).join('')}</div></article>`).join('')}</div><p class="evidenceDisclaimer112">هذه اقتراحات لتنظيم وتقوية ملف الشواهد، وليست حكمًا رسميًا بتحقق مؤشر. أرفق فقط ما نُفذ أو توفر فعليًا.</p></section>`}
export function evidencePage(state){const contextual=state.metadata?.contextEvidence85||[],suggestions=uniq([...contextual,...evidenceItems(state)]),selected=state.answers?.evidence||[],otherOn=Boolean(state.metadata?.otherEvidenceEnabled),files=state.attachments||[],chosen=selectedEvidence(state);const advice=!chosen.length&&!files.length&&!state.metadata?.evidenceLink?'<div class="warn compact">لم تضف شاهدًا أو مرفقًا بعد. يمكنك المتابعة، لكن الوثيقة ستكون دون مرفقات داعمة.</div>':'<div class="helperBox"><b>الشواهد جزء من العمل الموثق</b><p>يعرض النظام ما لديك أولًا، ثم الشواهد المناسبة للعائلة، ثم الاقتراحات المرجعية المرتبطة بطبيعة الوثيقة.</p></div>';const nonImages=files.map((f,i)=>({f,i})).filter(x=>!(x.f.type||'').startsWith('image/'));return `<section class="card evidenceStep"><button class="linkBtn" data-action="edit-description">→ رجوع</button><div class="stepBadge">الشواهد</div><h1>الشواهد والمرفقات</h1><p class="lead">أضف ما يثبت العمل فعلًا. لن يعتبر النظام مجرد اختيار شاهد دليلًا على تحقق مؤشر رسمي.</p><section class="evidenceCurrent112"><div class="sectionTitleRow"><div><b>الشواهد الموجودة الآن</b><small>ما اخترته أو أرفقته في هذه الوثيقة</small></div></div>${currentEvidence112(state,files)}</section><section class="evidenceSuggested112"><div class="sectionTitleRow"><div><b>الشواهد المناسبة لهذا العمل</b><small>اختر فقط ما لديك فعلًا</small></div></div><div class="chips choiceGrid">${suggestions.map(x=>`<button class="chip ${selected.includes(x)?'on':''}" data-evidence="${esc(x)}">${esc(x)}</button>`).join('')}<button class="chip ${otherOn?'on':''}" data-action="toggle-other-evidence">شاهد آخر</button></div>${otherOn?`<label class="fullField"><span>اكتب اسم الشاهد</span><input id="otherEvidence" value="${esc(state.metadata?.otherEvidence||'')}"></label>`:''}</section>${sourceGuidance112(state)}${advice}<div class="uploadPanel"><label class="uploadPrimary"><span class="uploadPrimaryIcon">＋</span><span><b>إرفاق صور أو ملفات</b><small>من الاستوديو أو تطبيق الملفات</small></span><input id="evidenceFiles" type="file" accept="image/*,.pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx,.txt,.csv" multiple hidden></label><label class="fullField linkField"><span>أو أضف رابط شاهد</span><input id="evidenceLink" inputmode="url" value="${esc(state.metadata?.evidenceLink||'')}" placeholder="https://..."></label></div>${imageThumbs(files)}${nonImages.length?`<div class="fileList"><b>الملفات المرفقة</b>${nonImages.map(({f,i})=>`<div class="fileRow"><span><b>${iconFor(f)}</b> <span>${esc(f.name)}</span> <small>${size(f.size)}</small></span><button class="linkBtn dangerText" data-remove-attachment="${i}">حذف</button></div>`).join('')}</div>`:''}<div class="row"><button class="btn primary" data-action="finalize">حفظ ومعاينة الوثيقة</button><button class="btn" data-action="finalize">المتابعة بدون مرفقات إضافية</button></div></section>`}

if(typeof document!=='undefined'&&!document.getElementById('analysis-evidence-chain117-style')){const s=document.createElement('style');s.id='analysis-evidence-chain117-style';s.textContent='.analysisEvidenceChain117{margin-top:18px;border:1px solid #d9e6e1;border-radius:16px;padding:14px;background:#fbfefd}.evidenceChainGrid117{display:grid;gap:8px;margin-top:12px}.evidenceChainItem117{display:grid;grid-template-columns:42px 1fr auto;gap:10px;align-items:center;border:1px solid #e1ebe7;border-radius:12px;padding:10px;background:#fff}.evidenceChainNo117{width:36px;height:36px;border-radius:10px;background:#eef7f4;display:grid;place-items:center;font-weight:900;color:#087c5c}.evidenceChainItem117 b{display:block;color:#173f38}.evidenceChainItem117 p{margin:3px 0 0;color:#667b74;font-size:12px;line-height:1.55}.evidenceChainItem117>small{font-size:10px;color:#71807b}.evidenceChainItem117.current{border-color:#a9dcca;background:#f5fbf8}.evidenceChainItem117.current .evidenceChainNo117{background:#07a869;color:#fff}.evidenceChainItem117.linked{border-color:#b9d7ec;background:#f7fbfe}.evidenceChainItem117.linked .evidenceChainNo117{background:#3d7eb9;color:#fff}.evidenceChainRule117{display:flex;gap:8px;align-items:flex-start;margin-top:10px;padding:10px 12px;border-radius:11px;background:#fff8e8;border:1px solid #eed9a6;font-size:12px}.evidenceChainRule117 b{white-space:nowrap;color:#93680d}@media(max-width:650px){.evidenceChainItem117{grid-template-columns:38px 1fr}.evidenceChainItem117>small{grid-column:2}}';document.head.appendChild(s)}
