import {esc} from './engine.js';
import {goalGroups65} from './goals65.js?v=76';
import {guideLinks76,strongGuideLinks76,selectedGuideDomains76,GUIDE_DOMAINS} from './guide-link76.js?v=76';
const clean=s=>String(s||'').replace(/\s+/g,' ').trim();
const uniq=a=>[...new Set((a||[]).map(clean).filter(Boolean))];
function indicatorGoals(i,s){if(i.code==='2-1-1-6'){const x=`${s.raw||''} ${s.topic||''}`;if(/قراءة|قرائي/.test(x)&&!/عدد|رياض/.test(x))return['تنمية المهارات القرائية الأساسية لدى الطلاب المستهدفين','رفع مستوى الإتقان في المهارات القرائية المستهدفة'];}const M={'2-1-1-4':['توظيف التقنية الرقمية في دعم تعلم الطلاب','تنويع خبرات التعلم من خلال أدوات رقمية مناسبة'],'2-1-1-5':['ربط التعلم بالتطبيق العملي بما يعزز فهم الطلاب','تنمية قدرة الطلاب على توظيف ما تعلموه في مواقف تطبيقية'],'2-1-1-7':['تنمية مهارات التفكير والبحث والابتكار لدى الطلاب','توفير فرص تعلم تدعم المبادرة وحل المشكلات'],'2-2-1-3':['توظيف نتائج التقويم في تحسين عمليات التعليم والتعلم','تحديد جوانب القوة والاحتياج وبناء إجراءات تعليمية مناسبة']};return M[i.code]||[]}
export function goalGroups76(s){const base=goalGroups65(s),smart=uniq(strongGuideLinks76(s).flatMap(i=>indicatorGoals(i,s))),all=uniq([...smart,...base.primary,...base.additional]);return{primary:all.slice(0,4),additional:all.slice(4,8)}}
function domainCard(s){const d=selectedGuideDomains76(s),p=guideLinks76(s)[0],editing=Boolean(s.metadata?.editGuideDomain76),relEditing=Boolean(s.metadata?.editRelatedDomain76);const buttons=Object.entries(GUIDE_DOMAINS).map(([id,name])=>`<button class="chip ${Number(id)===d.primary?'on':''}" data-guide-domain76="${id}">${esc(name)}</button>`).join('');const relButtons=Object.entries(GUIDE_DOMAINS).filter(([id])=>Number(id)!==d.primary).map(([id,name])=>`<button class="chip ${Number(id)===d.related?'on':''}" data-guide-related76="${id}">${esc(name)}</button>`).join('');return `<div class="helperBox" style="margin-bottom:16px"><b>الارتباط بالدليل</b><p><strong>المجال:</strong> ${esc(d.primaryName||'لم يحدد بعد')} <button class="linkBtn" data-action="toggle-guide-domain76">تعديل المجال</button></p>${editing?`<div class="chips choiceGrid">${buttons}</div>`:''}${p?`<p><strong>المؤشر المرتبط:</strong> ${esc(p.text)}</p><p class="questionHelp">${esc(p.reason||'ارتباط مقترح من المحرك.')}</p><small>رمز المؤشر: ${esc(p.code)} — ${esc(p.strength)}</small>`:'<p class="questionHelp">لا يوجد مؤشر موثوق داخل المجال المختار حتى الآن.</p>'}<p><button class="linkBtn" data-action="toggle-related-domain76">${d.related?'تعديل المجال المرتبط':'إضافة مجال مرتبط'}</button></p>${relEditing?`<div class="chips choiceGrid">${relButtons}<button class="chip" data-guide-related76="0">بدون مجال إضافي</button></div>`:''}${d.related?`<p class="questionHelp">المجال المرتبط: ${esc(d.relatedName)}</p>`:''}</div>`}
export function goalsPage76(s){const {primary,additional}=goalGroups76(s),selected=s.answers?.goals||[],other=Boolean(s.metadata?.otherGoalEnabled);const button=x=>`<button type="button" class="chip ${selected.includes(x)?'on':''}" data-goal="${esc(x)}">${esc(x)}</button>`;return `<section class="card"><button class="linkBtn" data-action="back-family-details">→ رجوع</button><div class="muted">الخطوة الثالثة</div><h1>الأهداف</h1><p class="lead">يقترح النظام المجال والمؤشر، ويمكنك تعديل المجال. عند التعديل يعاد بناء المؤشرات والأهداف على المجال المعتمد.</p>${domainCard(s)}<div class="chips choiceGrid">${primary.map(button).join('')}</div>${additional.length?`<details style="margin-top:14px"><summary class="btn">عرض أهداف إضافية</summary><div class="chips choiceGrid" style="margin-top:12px">${additional.map(button).join('')}</div></details>`:''}<div class="chips choiceGrid" style="margin-top:12px"><button type="button" class="chip ${other?'on':''}" data-action="toggle-other-goal">أخرى</button></div>${other?`<label class="fullField"><span>اكتب الهدف</span><input id="otherGoal" value="${esc(s.metadata.otherGoal||'')}"></label>`:''}<div class="row"><button class="btn primary" data-action="go-description">التالي: العنوان</button></div></section>`}
