import {esc} from './engine.js';
import {goalGroups65} from './goals65.js?v=76';
import {guideLinks76,strongGuideLinks76,selectedGuideDomains76,GUIDE_DOMAINS} from './guide-link76.js?v=89';
const clean=s=>String(s||'').replace(/\s+/g,' ').trim();
const uniq=a=>[...new Set((a||[]).map(clean).filter(Boolean))];
function subjects(s){return String(s.metadata?.familyDetails?.subject94||'').split('|||').filter(Boolean)}
function contextualGoals(s){const sub=subjects(s)[0]||'',x=`${s.raw||''} ${s.topic||''}`;if(/العربية|كفايات|لغوية/.test(sub)){if(/خط|كتابة/.test(x))return['تحسين وضوح الخط وتنظيم الكتابة لدى الطلاب','تنمية قدرة الطلاب على تطبيق قواعد الخط والكتابة بدقة','تعزيز العناية بجودة الكتابة وإخراجها'];if(/قراء|فهم قرائي/.test(x))return['رفع مستوى الطلاقة والفهم القرائي','تنمية قدرة الطلاب على فهم النصوص وتحليلها','تعزيز الدافعية نحو القراءة المستمرة'];return['تنمية المهارات اللغوية المستهدفة','رفع مستوى التطبيق اللغوي الصحيح','تعزيز الثقة في استخدام اللغة']}
if(/رياضيات/.test(sub)){const topic=/كسور/.test(x)?'الكسور':/جدول الضرب|الضرب/.test(x)?'جدول الضرب':/معادلات/.test(x)?'المعادلات':'المهارة الرياضية المستهدفة';return[`رفع مستوى إتقان ${topic} لدى الطلاب`,`تنمية القدرة على تطبيق ${topic} في مواقف متنوعة`,'تقليل الأخطاء المتكررة وتحسين دقة الحل']}
if(/علوم|أحياء|كيمياء|فيزياء/.test(sub)){const topic=/تجرب|مختبر/.test(x)?'التجريب والاستقصاء العلمي':sub;return[`تنمية الفهم العلمي المرتبط بـ${topic}`,'تنمية مهارات الاستقصاء والملاحظة والتجريب','ربط المفاهيم العلمية بالتطبيق العملي']}
if(/إنجليزية/.test(sub)){const topic=/مفردات|vocabulary/i.test(x)?'المفردات':/تحدث|speaking/i.test(x)?'التحدث':/استماع|listening/i.test(x)?'الاستماع':'المهارة المستهدفة';return[`تنمية مهارات اللغة الإنجليزية المرتبطة بـ${topic}`,'رفع مستوى الثقة في التواصل باللغة الإنجليزية','زيادة الممارسة الفعلية للمهارة المستهدفة']}
return[]}
function indicatorGoals(i,s){if(i.code==='2-1-1-6'){const x=`${s.raw||''} ${s.topic||''}`;if(/قراءة|قرائي/.test(x)&&!/عدد|رياض/.test(x))return['تنمية المهارات القرائية الأساسية لدى الطلاب المستهدفين','رفع مستوى الإتقان في المهارات القرائية المستهدفة'];}const M={'2-1-1-4':['توظيف التقنية الرقمية في دعم تعلم الطلاب','تنويع خبرات التعلم من خلال أدوات رقمية مناسبة'],'2-1-1-5':['ربط التعلم بالتطبيق العملي بما يعزز فهم الطلاب','تنمية قدرة الطلاب على توظيف ما تعلموه في مواقف تطبيقية'],'2-1-1-7':['تنمية مهارات التفكير والبحث والابتكار لدى الطلاب','توفير فرص تعلم تدعم المبادرة وحل المشكلات'],'2-2-1-3':['توظيف نتائج التقويم في تحسين عمليات التعليم والتعلم','تحديد جوانب القوة والاحتياج وبناء إجراءات تعليمية مناسبة']};return M[i.code]||[]}
export function goalGroups76(s){const contextual=contextualGoals(s),base=goalGroups65(s),smart=uniq(strongGuideLinks76(s).flatMap(i=>indicatorGoals(i,s)));const all=contextual.length?uniq([...contextual,...smart,...base.primary,...base.additional]):uniq([...smart,...base.primary,...base.additional]);return{primary:all.slice(0,8),additional:[]}}
function domainCard(s){const d=selectedGuideDomains76(s),p=guideLinks76(s)[0],editing=Boolean(s.metadata?.editGuideDomain76),relEditing=Boolean(s.metadata?.editRelatedDomain76);const buttons=Object.entries(GUIDE_DOMAINS).map(([id,name])=>`<button class="chip ${Number(id)===d.primary?'on':''}" data-guide-domain76="${id}">${esc(name)}</button>`).join('');const relButtons=Object.entries(GUIDE_DOMAINS).filter(([id])=>Number(id)!==d.primary).map(([id,name])=>`<button class="chip ${Number(id)===d.related?'on':''}" data-guide-related76="${id}">${esc(name)}</button>`).join('');return `<div class="helperBox" style="margin-bottom:16px"><b>ارتباط العمل بالتقويم المدرسي</b><p><strong>المجال:</strong> ${esc(d.primaryName||'لم يحدد بعد')} <button class="linkBtn" data-action="toggle-guide-domain76">تعديل</button></p>${editing?`<div class="chips choiceGrid">${buttons}</div>`:''}${p?`<p><strong>الممارسة التي يدعمها العمل:</strong> ${esc(p.text)}</p><p class="questionHelp">${esc(p.reason||'اقترح المحرك هذا الارتباط بناءً على محتوى العمل.')}</p><details class="indicatorDetails"><summary class="linkBtn">عرض التفاصيل الفنية</summary><p class="questionHelp">الرمز الرسمي: ${esc(p.code)} — قوة الارتباط: ${esc(p.strength)}</p></details>`:'<p class="questionHelp">لم يجد المحرك ارتباطًا موثوقًا بعد. أكمل بيانات العمل أو عدّل المجال عند الحاجة.</p>'}<p><button class="linkBtn" data-action="toggle-related-domain76">${d.related?'تعديل المجال الإضافي':'إضافة مجال آخر عند الحاجة'}</button></p>${relEditing?`<div class="chips choiceGrid">${relButtons}<button class="chip" data-guide-related76="0">بدون مجال إضافي</button></div>`:''}${d.related?`<p class="questionHelp">مجال إضافي داعم: ${esc(d.relatedName)}</p>`:''}</div>`}
export function goalsPage76(s){const {primary}=goalGroups76(s),selected=s.answers?.goals||[],other=Boolean(s.metadata?.otherGoalEnabled);const button=x=>`<button type="button" class="chip ${selected.includes(x)?'on':''}" data-goal="${esc(x)}">${esc(x)}</button>`;return `<section class="card"><button class="linkBtn" data-action="back-family-details">→ رجوع</button><div class="muted">الخطوة الثالثة</div><h1>الأهداف</h1><p class="lead">اختر الهدف أو الأهداف التي تناسب عملك. لا يحدد النظام أي هدف نيابةً عنك.</p>${domainCard(s)}<div class="chips choiceGrid">${primary.map(button).join('')}</div><div class="chips choiceGrid" style="margin-top:12px"><button type="button" class="chip ${other?'on':''}" data-action="toggle-other-goal">أخرى</button></div>${other?`<label class="fullField"><span>اكتب الهدف</span><input id="otherGoal" value="${esc(s.metadata.otherGoal||'')}"></label>`:''}<div class="row"><button class="btn primary" data-action="go-description">التالي: العنوان</button></div></section>`}
