const WORDS=new Map([
['تنفيد','تنفيذ'],['التنفيد','التنفيذ'],['ينفد','ينفذ'],['نفد','نفذ'],['المستفدين','المستفيدين'],['المستفيدن','المستفيدين'],['الطلابء','الطلاب'],['المدرسه','المدرسة'],['مدرسه','مدرسة'],['المعلميين','المعلمين'],['المعلمينن','المعلمين'],['النتايج','النتائج'],['نتايج','نتائج'],['الاهداف','الأهداف'],['اهداف','أهداف'],['الاجراءات','الإجراءات'],['اجراءات','إجراءات'],['الاداء','الأداء'],['التقيم','التقييم'],['التقيم','التقييم'],['الامن','الأمن'],['السلامه','السلامة'],['الاداره','الإدارة'],['الادارية','الإدارية'],['الاداري','الإداري'],['الانشطه','الأنشطة'],['انشطه','أنشطة'],['الانتماء','الانتماء'],['الاثر','الأثر'],['اثره','أثره'],['الاثرية','الأثرية'],['الاخلاء','الإخلاء'],['الاسعافات','الإسعافات'],['الاول','الأول'],['الاولى','الأولى'],['المسول','المسؤول'],['المسؤل','المسؤول'],['مسول','مسؤول'],['البيئه','البيئة'],['مهاره','مهارة'],['المهاره','المهارة'],['الفعاليه','الفعالية'],['التوعيه','التوعية'],['المشاركه','المشاركة'],['المبادره','المبادرة'],['الخطه','الخطة'],['خطه','خطة'],['المرحله','المرحلة'],['العمليه','العملية'],['القرائه','القراءة'],['قراءه','قراءة'],['الوطنيه','الوطنية'],['اللغويه','اللغوية'],['الرقميه','الرقمية'],['الالكتروني','الإلكتروني'],['الالكترونية','الإلكترونية'],['الكتروني','إلكتروني'],['الكترونية','إلكترونية']
]);
const SKIP=new Set(['executorName','count','evidenceLink','dateISO']);
const arabicWord=/[\u0621-\u064A]{2,}/g;
const clean=s=>String(s||'');
function wordSuggestions(text){const out=[];const seen=new Set();for(const m of clean(text).matchAll(arabicWord)){const w=m[0],to=WORDS.get(w);if(to&&to!==w&&!seen.has(`${w}:${to}`)){seen.add(`${w}:${to}`);out.push({kind:'word',from:w,to,label:'إملاء'})}if(/([\u0621-\u064A])\1{2,}/u.test(w)&&!seen.has(`repeat:${w}`)){seen.add(`repeat:${w}`);out.push({kind:'unknown',from:w,to:'',label:'كلمة غير واضحة'})}}return out}
function punctuationSuggestions(text){const s=clean(text),out=[];if(/\s{2,}/.test(s))out.push({kind:'format',from:'مسافات متكررة',to:'مسافة واحدة',label:'تنسيق'});if(/\s+[،؛؟.!]/.test(s))out.push({kind:'format',from:'مسافة قبل علامة الترقيم',to:'إزالة المسافة',label:'ترقيم'});if(/[،,؛;:.!?؟]{2,}/.test(s))out.push({kind:'format',from:'علامات ترقيم متكررة',to:'علامة واحدة',label:'ترقيم'});return out}
export function proofread91(text){return [...wordSuggestions(text),...punctuationSuggestions(text)].slice(0,12)}
export function applyProof91(text,item){let s=clean(text);if(item.kind==='word'&&item.to)return s.replaceAll(item.from,item.to);if(item.kind==='format'){s=s.replace(/\s{2,}/g,' ').replace(/\s+([،؛؟.!])/g,'$1').replace(/([،؛؟.!])\1+/g,'$1').replace(/,+/g,'،').replace(/\?+/g,'؟');}return s}
function eligible(el){if(!el||SKIP.has(el.id)||el.type==='date'||el.type==='file'||el.type==='number'||el.type==='url')return false;if(el.dataset.noProof==='1')return false;return el.matches('textarea,input[type="text"],input:not([type])')}
function removeBox(el){const old=el.parentElement?.querySelector(`.proof91[data-for="${CSS.escape(el.id||'anon')}"]`);if(old)old.remove()}
function render(el){if(!eligible(el))return;removeBox(el);const issues=proofread91(el.value);if(!issues.length)return;const box=document.createElement('div');box.className='proof91';box.dataset.for=el.id||'anon';const actionable=issues.filter(x=>x.kind!=='unknown');box.innerHTML=`<div class="proof91Head"><b>مراجعة الكتابة</b><small>${issues.length} ملاحظة</small></div><div class="proof91Items">${issues.map((x,i)=>x.kind==='unknown'?`<span class="proof91Warn">راجع: <b>${x.from}</b></span>`:`<button type="button" class="proof91Fix" data-proof-i="${i}"><del>${x.from}</del> ← <b>${x.to}</b></button>`).join('')}</div>${actionable.length>1?'<button type="button" class="proof91All">تصحيح الواضح كله</button>':''}`;el.insertAdjacentElement('afterend',box);box.addEventListener('click',e=>{const b=e.target.closest('[data-proof-i]');if(b){el.value=applyProof91(el.value,issues[Number(b.dataset.proofI)]);el.dispatchEvent(new Event('input',{bubbles:true}));render(el);el.focus();return}if(e.target.closest('.proof91All')){let v=el.value;for(const x of actionable)v=applyProof91(v,x);el.value=v;el.dispatchEvent(new Event('input',{bubbles:true}));render(el);el.focus()}})}
let timer=null;function schedule(el){clearTimeout(timer);timer=setTimeout(()=>render(el),380)}
export function installProofreader91(root=document){root.addEventListener('input',e=>{if(eligible(e.target))schedule(e.target)},true);root.addEventListener('blur',e=>{if(eligible(e.target))render(e.target)},true);const obs=new MutationObserver(()=>root.querySelectorAll('textarea,input').forEach(el=>{if(eligible(el)){el.lang='ar';el.spellcheck=true;el.setAttribute('autocorrect','on')}}));obs.observe(root,{childList:true,subtree:true});root.querySelectorAll('textarea,input').forEach(el=>{if(eligible(el)){el.lang='ar';el.spellcheck=true;el.setAttribute('autocorrect','on')}})}
