import {ENTRY} from './config.js';
import {esc,joinAr,familyOptions,subtypeOptions,potentialLinks} from './engine.js';
import {displayAudiences,smartTitle,titleCandidates,selectedGoals,suggestedGoals,executionDescription,evidenceItems} from './output-quality.js';

const AUDIENCES=['الطلاب','المعلمون','أولياء الأمور','الإداريون','جميع منسوبي المدرسة','مستفيدون آخرون'];
const DURATIONS=['','حصة دراسية','حصتان دراسيتان','يوم دراسي','يومان','أسبوع','أسبوعان','شهر','فصل دراسي','مدة أخرى'];
const PLACES=['','فصل دراسي','مركز مصادر التعلم','المكتبة','معمل الحاسب','المختبر','المسرح المدرسي','المصلى','ساحة المدرسة','الملعب','غرفة النشاط','قاعة التدريب','مكتب الإدارة','عن بُعد','خارج المدرسة','مكان آخر'];
const options=(items,current,placeholder)=>items.map(x=>`<option value="${esc(x)}" ${x===current?'selected':''}>${esc(x||placeholder)}</option>`).join('');

export function landing(){return `<section class="card"><div class="kicker">V10 Stable Core · نسخة تطوير مستقرة</div><h1>ماذا تريد أن تنجز؟</h1><p class="lead">صف ما حدث بطريقتك، أو ابدأ مباشرة من نوع العمل.</p><button class="smartEntry" data-entry="smart"><span>✨</span><span><b>صف لي ما حدث</b><small>المحرك يحدد النوع ويكشف التعارضات قبل المتابعة</small></span><span>←</span></button><div class="dividerText"><span>أو ابدأ مباشرة</span></div><div class="entryGrid">${['report','minutes','analysis','plan','program','pd','follow'].map(k=>`<button class="entryTile" data-entry="${k}"><span>${ENTRY[k].icon}</span><b>${ENTRY[k].label}</b></button>`).join('')}</div></section>`}
export function entryForm(intent){const e=ENTRY[intent]||ENTRY.smart;return `<section class="card"><button class="linkBtn" data-action="home">→ رجوع</button><div class="badge">${e.icon} ${e.label}</div><h1>${e.title}</h1><p class="lead">${e.help}</p><textarea id="raw" lang="ar" spellcheck="true" autocorrect="on" placeholder="${esc(e.placeholder)}"></textarea><div class="row"><button class="btn primary" data-action="analyze">افهم وأكمل</button></div></section>`}

export function understanding(state){
 const c=state.classification,conflict=c.conflict?`<div class="warn"><b>وجدت تعارضًا يحتاج قرارك.</b><p>أنت دخلت من <strong>${esc(c.hinted)}</strong>، بينما وصفك أقرب إلى <strong>${esc(c.detected)}</strong>.</p><div class="row"><button class="btn primary" data-action="accept-detected">اعتماد فهم المحرك</button><button class="btn" data-action="accept-hint">الاستمرار حسب اختياري</button></div></div>`:'';
 const suggested=state.suggestedAudiences?.length?`<p class="questionHelp">فهمت من وصفك أن المستفيدين قد يكونون: <b>${esc(joinAr(state.suggestedAudiences))}</b>. اختر بنفسك للتأكيد.</p>`:`<p class="questionHelp">اختر المستفيدين الفعليين من العمل.</p>`;
 const titles=titleCandidates(state),selectedTitle=state.metadata.selectedTitle||'';
 return `<section class="card"><div class="muted">فهم المحرك</div><div class="under">${esc(smartTitle(state))}</div>${conflict}
 <div class="chooser"><small>العنوان المقترح</small><p class="questionHelp">اختر العنوان الأقرب، أو عدله بنفسك.</p><div class="chips choiceGrid">${titles.map(x=>`<button class="chip ${(selectedTitle===x||(!selectedTitle&&!state.metadata.titleManual&&x===titles[0]))?'on':''}" data-title-choice="${esc(x)}">${esc(x)}</button>`).join('')}</div><label class="fullField"><span>تعديل العنوان يدويًا</span><input id="workTitle" value="${esc(state.metadata.titleManual?state.metadata.workTitle:(selectedTitle||titles[0]||state.metadata.workTitle))}" placeholder="يمكنك تعديل العنوان هنا"></label></div>
 <div class="editGrid"><label><span>المنفذ</span><input id="executorName" value="${esc(state.metadata.executorName)}" placeholder="اسم المنفذ"></label><label><span>العدد</span><input id="count" inputmode="numeric" value="${esc(state.metadata.count)}" placeholder="عدد المستفيدين"></label><label><span>التاريخ</span><input id="dateISO" type="date" value="${esc(state.metadata.dateISO||'')}"></label></div>
 <div class="editGrid"><label><span>المجال</span><input id="domainEdit" value="${esc(c.domain||'')}" placeholder="اكتب المجال أو عدله"></label><label><span>الموضوع</span><input id="topicEdit" value="${esc(state.topic||'')}" placeholder="اكتب موضوع العمل"></label></div>
 <div class="editGrid"><label><span>المدة</span><select id="durationSelect">${options(DURATIONS,state.metadata.durationChoice||'','اختر المدة')}</select></label><label><span>مكان التنفيذ</span><select id="placeSelect">${options(PLACES,state.metadata.placeChoice||'','اختر المكان')}</select></label></div>
 ${state.metadata.durationChoice==='مدة أخرى'?`<label class="fullField"><span>اكتب المدة</span><input id="customDuration" value="${esc(state.metadata.customDuration||'')}" placeholder="مثال: ثلاث حصص خلال أسبوع"></label>`:''}
 ${state.metadata.placeChoice==='مكان آخر'?`<label class="fullField"><span>اكتب مكان التنفيذ</span><input id="customPlace" value="${esc(state.metadata.customPlace||'')}" placeholder="اكتب المكان"></label>`:''}
 <div class="chooser"><small>من المستفيدون من العمل؟</small>${suggested}<div class="chips choiceGrid">${AUDIENCES.map(x=>`<button class="chip ${(state.audiences||[]).includes(x)?'on':''}" data-audience="${esc(x)}">${esc(x)}</button>`).join('')}</div>${(state.audiences||[]).includes('مستفيدون آخرون')?`<label class="fullField"><span>من هم المستفيدون الآخرون؟</span><input id="otherAudience" value="${esc(state.metadata.otherAudience||'')}" placeholder="مثال: الزوار، المجتمع المحلي، طلاب مدرسة أخرى"></label>`:''}</div>
 <div class="chooser"><small>عائلة العمل</small><div class="chips">${familyOptions().map(x=>`<button class="chip ${x===c.type?'on':''}" data-type="${esc(x)}">${esc(x)}</button>`).join('')}</div></div>
 <div class="chooser"><small>النوع الفرعي</small><div class="chips">${subtypeOptions(state).map(x=>`<button class="chip ${x===c.subtype?'on':''}" data-subtype="${esc(x)}">${esc(x)}</button>`).join('')}</div></div>
 <div class="row"><button class="btn primary" data-action="go-goals">التالي: الأهداف</button><button class="btn" data-action="home">بداية جديدة</button></div></section>`
}

export function goalsPage(state){const opts=suggestedGoals(state),selected=state.answers.goals||[],otherOn=Boolean(state.metadata.otherGoalEnabled),other=state.metadata.otherGoal||'';return `<section class="card"><button class="linkBtn" data-action="understanding">→ رجوع</button><div class="muted">الخطوة الثانية</div><h1>الأهداف</h1><p class="lead">اختر أي عدد من الأهداف التي تناسب العمل، أو اختر «أخرى» واكتب هدفك.</p><div class="chips choiceGrid">${opts.map(x=>`<button class="chip ${selected.includes(x)?'on':''}" data-goal="${esc(x)}">${esc(x)}</button>`).join('')}<button class="chip ${otherOn?'on':''}" data-action="toggle-other-goal">أخرى</button></div>${otherOn?`<label class="otherGoalBox"><span>اكتب الهدف</span><input id="otherGoal" value="${esc(other)}" placeholder="اكتب الهدف بصياغتك"></label>`:''}<div class="row"><button class="btn primary" data-action="go-description">التالي: وصف التنفيذ ومخرجاته</button><button class="btn" data-action="understanding">رجوع</button></div></section>`}
export function descriptionPage(state){const generated=state.metadata.generatedDescription||executionDescription(state);return `<section class="card"><button class="linkBtn" data-action="go-goals">→ رجوع</button><div class="muted">الخطوة الثالثة</div><h1>وصف التنفيذ ومخرجاته</h1><p class="lead">هذا النص بُني من بيانات العمل والأهداف التي اخترتها. عدله مباشرة إذا رغبت.</p><textarea id="generatedDescription" class="descriptionEditor" spellcheck="true" autocorrect="on">${esc(generated)}</textarea><div class="row"><button class="btn primary" data-action="finalize">اعتماد وإنشاء الوثيقة</button><button class="btn" data-action="regenerate-description">إعادة توليد النص من المدخلات</button></div></section>`}
export function ready(state){const title=smartTitle(state),goals=selectedGoals(state),description=state.metadata.generatedDescription||executionDescription(state),evidence=evidenceItems(state),aud=displayAudiences(state),meta=[];if(state.metadata.executorName)meta.push(['المنفذ',state.metadata.executorName]);if(state.metadata.dateDisplay)meta.push(['التاريخ',state.metadata.dateDisplay]);if(state.metadata.place)meta.push(['مكان التنفيذ',state.metadata.place]);if(state.metadata.duration)meta.push(['المدة',state.metadata.duration]);if(aud.length)meta.push(['المستفيدون',joinAr(aud)]);if(state.metadata.count)meta.push(['العدد',state.metadata.count]);if(state.grades.length)meta.push(['الصفوف',joinAr(state.grades)]);return `<section class="card documentHead"><div class="muted">عنوان الوثيقة</div><div class="title">${esc(title)}</div>${meta.length?`<div class="docMeta">${meta.map(([k,v])=>`<div><small>${esc(k)}</small><b>${esc(v)}</b></div>`).join('')}</div>`:''}</section><section class="card"><h2>الأهداف</h2>${goals.length?`<ul class="smartList">${goals.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:`<p class="muted">لم يتم اختيار أهداف.</p>`}</section><section class="card"><h2>وصف التنفيذ ومخرجاته</h2><div class="narrative"><p>${esc(description)}</p></div></section><section class="card"><h2>الشواهد</h2><ul class="smartList">${evidence.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><details><summary>الارتباطات المحتملة</summary>${potentialLinks(state).map(x=>`<div class="fact">${esc(x)}</div>`).join('')}<div class="warn compact">هذه ارتباطات محتملة وليست حكمًا بتحقق مؤشر.</div></details></section><div class="toolbar"><button class="btn" data-action="edit-description">تعديل الوصف</button><button class="btn" data-action="go-goals">تعديل الأهداف</button><button class="btn" data-action="understanding">تعديل البيانات</button></div>`}
