import {esc} from './engine.js';
const RULES=[
['تنفيد','تنفيذ','إملاء'],['التنفيد','التنفيذ','إملاء'],['المستفدين','المستفيدين','إملاء'],['المستفيدن','المستفيدين','إملاء'],['المدرسه','المدرسة','إملاء'],['المعلميين','المعلمين','إملاء'],['المعلمينن','المعلمين','إملاء'],['النتايج','النتائج','إملاء'],['الاهداف','الأهداف','إملاء'],['الاجراءات','الإجراءات','إملاء'],['الاداء','الأداء','إملاء'],['التقيم','التقييم','إملاء'],['التقييمم','التقييم','إملاء'],['الامن','الأمن','إملاء'],['السلامه','السلامة','إملاء'],['المبادره','المبادرة','إملاء'],['المسابقه','المسابقة','إملاء'],['الفعاليه','الفعالية','إملاء'],['الخطه','الخطة','إملاء'],['القراءه','القراءة','إملاء'],['الكتابه','الكتابة','إملاء'],['المهاره','المهارة','إملاء'],['البيئه','البيئة','إملاء'],['الاداري','الإداري','إملاء'],['الادارية','الإدارية','إملاء'],['الاثر','الأثر','إملاء'],['الانجاز','الإنجاز','إملاء'],['الاستفاده','الاستفادة','إملاء'],['المسؤليه','المسؤولية','إملاء'],['المسؤوليه','المسؤولية','إملاء'],['الرقميه','الرقمية','إملاء'],['الوطنيه','الوطنية','إملاء'],['الايجابي','الإيجابي','إملاء'],['الايجابية','الإيجابية','إملاء'],['الطلابء','الطلاب','إملاء'],
['تم تم','تم','إزالة تكرار'],['من خلال من خلال','من خلال','إزالة تكرار'],['بهدف بهدف','بهدف','إزالة تكرار'],['في في','في','إزالة تكرار'],['على على','على','إزالة تكرار'],[' ،','،','ترقيم'],[' .','.','ترقيم'],[' ؛','؛','ترقيم'],[' ؟','؟','ترقيم'],['،،','،','ترقيم'],[',,','،','ترقيم'],['??','؟','ترقيم'],['..','.','ترقيم'],['!!','!','ترقيم'],['|||','، ','تنسيق']
];
const uniq=a=>[...new Set(a)];
export function suggestions108(text){const s=String(text||''),out=[];for(const [from,to,label] of RULES)if(s.includes(from))out.push({from,to,label,id:`${label}:${from}`});const spaces=s.match(/\s{2,}/g)||[];if(spaces.length)out.push({from:spaces[0],to:' ',label:'مسافات',id:'spaces'});return out.slice(0,12)}
export function qualityIssues108(text){const s=String(text||''),out=[],tokens=s.match(/[\u0621-\u064A]{2,}/g)||[];for(const t of uniq(tokens)){if(/([\u0621-\u064A])\1{2,}/u.test(t))out.push({token:t,id:`repeat:${t}`,label:'تكرار حروف غير طبيعي'});}if(/\|{2,}/.test(s))out.push({token:'|||',id:'separator',label:'فاصل تقني ظاهر'});return out.slice(0,10)}
export function applySuggestion108(text,from,to){return String(text||'').split(from).join(to)}
function panelFor(el){let p=el.nextElementSibling;if(p?.classList?.contains('liveProof108'))return p;p=document.createElement('div');p.className='liveProof108';p.hidden=true;el.insertAdjacentElement('afterend',p);return p}
function refresh(el){const p=panelFor(el),s=suggestions108(el.value),issues=qualityIssues108(el.value);if(!s.length&&!issues.length){p.hidden=true;p.innerHTML='';return}p.hidden=false;p.innerHTML=`<div class="liveProofHead108"><b>مراجعة لغوية</b><small>${s.length?'اقتراحات جاهزة':'راجع الكلمة المعلّمة'}</small></div>${s.map(x=>`<button type="button" class="liveProofFix108" data-proof-from="${esc(x.from)}" data-proof-to="${esc(x.to)}"><span>${esc(x.label)}</span><del>${esc(x.from)}</del><b>${esc(x.to)}</b></button>`).join('')}${issues.map(x=>`<div class="liveProofIssue108">${esc(x.label)}: <b>${esc(x.token)}</b></div>`).join('')}`}
export function attachLiveProofreader108(root=document){root.querySelectorAll('textarea,input[type="text"],input:not([type])').forEach(el=>{if(el.dataset.proofBound108)return;el.dataset.proofBound108='1';el.lang='ar';el.spellcheck=true;el.setAttribute('autocorrect','on');el.addEventListener('input',()=>refresh(el));el.addEventListener('blur',()=>refresh(el));refresh(el)});}
document.addEventListener('click',e=>{const b=e.target.closest('[data-proof-from]');if(!b)return;const p=b.closest('.liveProof108'),el=p?.previousElementSibling;if(!el)return;el.value=applySuggestion108(el.value,b.dataset.proofFrom,b.dataset.proofTo);el.dispatchEvent(new Event('input',{bubbles:true}));refresh(el)},true);
export function unresolvedQualityIssues108(state){const ignored=new Set(state.metadata?.ignoredQualityIssues76||[]);return qualityIssues108(state.metadata?.generatedDescription||'').filter(x=>!ignored.has(x.id))}
export function spellingPage108(state){const text=state.metadata.generatedDescription||'',suggestions=suggestions108(text),issues=unresolvedQualityIssues108(state),blocking=issues.length>0;return `<section class="card"><button class="linkBtn" data-action="edit-description">→ رجوع</button><div class="muted">مراجعة لغوية وإملائية</div><h1>${blocking?'يوجد نص يحتاج مراجعة':'المراجعة النهائية'}</h1><p class="lead">المدقق يعمل الآن أثناء الكتابة في جميع الحقول القابلة للتعديل، وهذه مراجعة أخيرة للنص قبل الشواهد.</p>${issues.map(x=>`<div class="fact" style="border-color:#b86"><small>${esc(x.label)}</small><b>${esc(x.token)}</b><div class="row"><button class="btn primary" data-action="edit-description">تعديل النص</button><button class="btn" data-quality-ignore76="${esc(x.id)}">الكلمة مقصودة</button></div></div>`).join('')}${suggestions.map(x=>`<div class="fact"><small>${esc(x.label)}</small><div style="font-size:1.05rem;margin:8px 0"><del>${esc(x.from)}</del> ← <b>${esc(x.to)}</b></div><div class="row"><button class="btn primary" data-spell76-from="${esc(x.from)}" data-spell76-to="${esc(x.to)}">استبدال بـ: ${esc(x.to)}</button></div></div>`).join('')}${!blocking&&!suggestions.length?'<div class="helperBox">النص سليم بحسب قواعد المراجعة الحالية.</div>':''}<div class="row">${blocking?'':'<button class="btn primary" data-action="go-evidence-direct">التالي: الشواهد</button>'}</div></section>`}
