import {esc} from './engine.js';
const RULES=[
['تنفيد','تنفيذ','تصحيح إملائي'],['التنفيد','التنفيذ','تصحيح إملائي'],['المستفدين','المستفيدين','تصحيح إملائي'],['الطلابء','الطلاب','تصحيح إملائي'],['المدرسه','المدرسة','تصحيح إملائي'],['المعلميين','المعلمين','تصحيح إملائي'],['النتايج','النتائج','تصحيح إملائي'],['الاهداف','الأهداف','تصحيح إملائي'],['الاجراءات','الإجراءات','تصحيح إملائي'],['الاداء','الأداء','تصحيح إملائي'],['التقيم','التقييم','تصحيح إملائي'],['|||','، ','تنسيق القائمة'],['||','، ','تنسيق القائمة'],['تم تم','تم','إزالة تكرار'],['من خلال من خلال','من خلال','إزالة تكرار'],['بهدف بهدف','بهدف','إزالة تكرار'],[' ،','،','علامة ترقيم'],[' .','.','علامة ترقيم'],[' ؛','؛','علامة ترقيم'],[' ؟','؟','علامة ترقيم'],['،،','،','علامة ترقيم'],['..','.','علامة ترقيم'],['،،','،','علامة ترقيم']
];
const uniq=a=>[...new Set(a)];
export function suggestions76(text){const s=String(text||''),out=[];for(const [from,to,label] of RULES)if(s.includes(from))out.push({type:'suggestion',from,to,label,id:`s:${from}`});const doubles=s.match(/\s{2,}/g)||[];if(doubles.length)out.push({type:'suggestion',from:doubles[0],to:' ',label:'مسافات زائدة',id:'spaces'});return out.slice(0,16)}
export function qualityIssues76(text){const s=String(text||''),out=[],tokens=s.match(/[\u0621-\u064A]{2,}/g)||[];for(const t of uniq(tokens)){if(/([\u0621-\u064A])\1{2,}/u.test(t))out.push({token:t,id:`repeat:${t}`,label:'كلمة مشوهة أو تكرار حروف غير طبيعي'});}if(/\|{2,}/.test(s))out.push({token:'|||',id:'raw-separator',label:'فاصل تقني غير صالح في النص النهائي'});if(/[،؛؟.!]\S/u.test(s))out.push({token:'علامة ترقيم',id:'punct-space',label:'تحتاج بعض علامات الترقيم إلى مسافة بعدها'});return out.slice(0,12)}
export function applySuggestion76(text,from,to){return String(text||'').split(from).join(to)}
export function unresolvedQualityIssues76(state){const ignored=new Set(state.metadata?.ignoredQualityIssues76||[]);return qualityIssues76(state.metadata?.generatedDescription||'').filter(x=>!ignored.has(x.id))}
export function spellingPage76(state){const text=state.metadata.generatedDescription||'',suggestions=suggestions76(text),issues=unresolvedQualityIssues76(state),blocking=issues.length>0;return `<section class="card"><button class="linkBtn" data-action="edit-description">→ رجوع</button><div class="muted">مراجعة لغوية وإملائية</div><h1>${blocking?'يوجد نص يحتاج مراجعة':'مراجعة النص'}</h1><p class="lead">يفحص النظام الإملاء، الكلمات المشوهة، الفواصل التقنية، المسافات وعلامات الترقيم قبل اعتماد النص.</p>${issues.map(x=>`<div class="fact" style="border-color:#b86"><small>${esc(x.label)}</small><b>${esc(x.token)}</b><div class="row"><button class="btn" data-action="edit-description">تعديل النص</button><button class="btn" data-quality-ignore76="${esc(x.id)}">تجاهل بعد المراجعة</button></div></div>`).join('')}${suggestions.map(x=>`<div class="fact"><small>${esc(x.label)}</small><b>${esc(x.from)} ← ${esc(x.to)}</b><div class="row"><button class="btn" data-spell76-from="${esc(x.from)}" data-spell76-to="${esc(x.to)}">اعتماد التصحيح</button></div></div>`).join('')}${!blocking&&!suggestions.length?'<div class="helperBox">لم أجد أخطاء إملائية أو علامات ترقيم واضحة تحتاج إلى مراجعة.</div>':''}<div class="row">${blocking?'':'<button class="btn primary" data-action="go-evidence-direct">التالي: الشواهد</button>'}</div></section>`}
