import {esc} from './engine.js';
const RULES=[
['الامن','الأمن','تصحيح إملائي'],['السلامه','السلامة','تصحيح إملائي'],['تنفيد','تنفيذ','تصحيح إملائي'],['التنفيد','التنفيذ','تصحيح إملائي'],['المستفدين','المستفيدين','تصحيح إملائي'],['الطلابء','الطلاب','تصحيح إملائي'],['المدرسه','المدرسة','تصحيح إملائي'],['المعلميين','المعلمين','تصحيح إملائي'],['النتايج','النتائج','تصحيح إملائي'],['الاهداف','الأهداف','تصحيح إملائي'],['الاجراءات','الإجراءات','تصحيح إملائي'],['الاداء','الأداء','تصحيح إملائي'],['التقيم','التقييم','تصحيح إملائي'],
['|||','، ','تنسيق القائمة'],['||','، ','تنسيق القائمة'],[',,','،','علامة ترقيم'],['??','؟','علامة ترقيم'],['،،','،','علامة ترقيم'],['..','.','علامة ترقيم'],['تم تم','تم','إزالة تكرار'],['من خلال من خلال','من خلال','إزالة تكرار'],['بهدف بهدف','بهدف','إزالة تكرار'],[' ،','،','علامة ترقيم'],[' .','.','علامة ترقيم'],[' ؛','؛','علامة ترقيم'],[' ؟','؟','علامة ترقيم']
];
const uniq=a=>[...new Set(a)];
export function suggestions77(text){const s=String(text||''),out=[];for(const [from,to,label] of RULES)if(s.includes(from))out.push({from,to,label,id:`s:${from}`});const doubles=s.match(/\s{2,}/g)||[];if(doubles.length)out.push({from:doubles[0],to:' ',label:'مسافات زائدة',id:'spaces'});return out.slice(0,20)}
export function qualityIssues77(text){const s=String(text||''),out=[],tokens=s.match(/[\u0621-\u064A]{2,}/g)||[];for(const t of uniq(tokens)){if(/([\u0621-\u064A])\1{2,}/u.test(t))out.push({token:t,id:`repeat:${t}`,label:'كلمة مشوهة أو تكرار حروف غير طبيعي'});}if(/\|{2,}/.test(s))out.push({token:'|||',id:'raw-separator',label:'فاصل تقني غير صالح'});return out.slice(0,12)}
export function applySuggestion77(text,from,to){return String(text||'').split(from).join(to)}
export function unresolvedQualityIssues77(state){const ignored=new Set(state.metadata?.ignoredQualityIssues77||[]);return qualityIssues77(state.metadata?.generatedDescription||'').filter(x=>!ignored.has(x.id))}
export function spellingPage77(state){const text=state.metadata.generatedDescription||'',suggestions=suggestions77(text),issues=unresolvedQualityIssues77(state),blocking=issues.length>0;return `<section class="card"><button class="linkBtn" data-action="edit-description">→ رجوع</button><div class="muted">مراجعة لغوية وإملائية</div><h1>${blocking?'يوجد نص يحتاج مراجعة':'مراجعة النص'}</h1><p class="lead">راجع كل اقتراح بزر واحد. الكلمات غير الواضحة لا يصححها النظام بالتخمين.</p>${issues.map(x=>`<div class="fact" style="border-color:#b86"><small>${esc(x.label)}</small><b>${esc(x.token)}</b><p class="questionHelp">لم أجد تصحيحًا موثوقًا لهذه الكلمة.</p><div class="row"><button class="btn primary" data-action="edit-description">تعديل الكلمة</button><button class="btn" data-quality-ignore77="${esc(x.id)}">الكلمة مقصودة</button></div></div>`).join('')}${suggestions.map(x=>`<div class="fact"><small>${esc(x.label)}</small><div style="font-size:1.05rem;margin:6px 0"><del>${esc(x.from)}</del> &larr; <b>${esc(x.to)}</b></div><div class="row"><button class="btn primary" data-spell77-from="${esc(x.from)}" data-spell77-to="${esc(x.to)}">استبدال بـ: ${esc(x.to)}</button></div></div>`).join('')}${!blocking&&!suggestions.length?'<div class="helperBox">لم أجد أخطاء إملائية أو علامات ترقيم واضحة تحتاج إلى مراجعة.</div>':''}<div class="row">${blocking?'':'<button class="btn primary" data-action="go-evidence-direct">التالي: الشواهد</button>'}</div></section>`}
