import {saveDraft109,loadDraft109,deleteDraft109,saveDocument109} from './document-repository106.js?v=109';
const LEGACY_DB='school-engine-v53',LEGACY_STORE='drafts',LEGACY_KEY='current';
function legacyOpen(){return new Promise((resolve,reject)=>{const r=indexedDB.open(LEGACY_DB,1);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains(LEGACY_STORE))db.createObjectStore(LEGACY_STORE)};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function legacyLoad(){try{const db=await legacyOpen();return await new Promise((resolve,reject)=>{const r=db.transaction(LEGACY_STORE,'readonly').objectStore(LEGACY_STORE).get(LEGACY_KEY);r.onsuccess=()=>resolve(r.result||null);r.onerror=()=>reject(r.error)})}catch{return null}}
async function legacyClear(){try{const db=await legacyOpen();return await new Promise(resolve=>{const tx=db.transaction(LEGACY_STORE,'readwrite');tx.objectStore(LEGACY_STORE).delete(LEGACY_KEY);tx.oncomplete=()=>resolve(true);tx.onerror=()=>resolve(false)})}catch{return false}}
export async function saveDraft(state,screen='understanding'){if(!state)return false;const rec=await saveDraft109(state,{screen});if(screen==='final')await saveDocument109(state,{id:rec.id,status:'final'});return true}
export async function loadDraft(){let rec=await loadDraft109();if(!rec){const old=await legacyLoad();if(old?.state){rec=await saveDraft109(old.state,{screen:old.screen||'understanding'});await legacyClear()}}if(!rec)return null;return{state:rec.state,screen:rec.screen||'understanding',savedAt:rec.updatedAt||rec.createdAt||Date.now(),id:rec.id}}
export async function clearDraft(){const a=await deleteDraft109();await legacyClear();return a}
export function formatSavedAt(ts){try{return new Intl.DateTimeFormat('ar-SA',{dateStyle:'medium',timeStyle:'short'}).format(new Date(ts))}catch{return''}}
