import {esc} from './engine.js';
import {bestTitle55,titleCandidates55,needsTitleClarification,clarificationOptions} from './title55.js';
export function titlePage56(s){
 if(needsTitleClarification(s)){
  const opts=clarificationOptions(s);
  return `<section class="card titleStep"><button class="linkBtn" data-action="go-goals">→ رجوع للأهداف</button><div class="stepBadge">الخطوة الثالثة</div><h1>نحتاج توضيحًا بسيطًا</h1><p class="lead">حتى لا ننشئ عنوانًا غير دقيق، اختر أقرب وصف للعمل الذي تقصده.</p><div class="clarifyList">${opts.map(x=>`<button class="choiceRow" data-title-clarify="${esc(x)}"><span>${esc(x)}</span><span>←</span></button>`).join('')}<button class="choiceRow" data-action="custom-title-clarification"><span>شيء آخر</span><span>+</span></button></div>${s.metadata?.showCustomTitleClarification?`<div class="editPanel"><label class="fullField"><span>اكتب العمل باختصار</span><input id="titleClarification" value="${esc(s.metadata?.titleClarification||'')}" placeholder="مثال: تحليل نتائج اختبار الفترة الأولى"></label><button class="btn primary fullBtn" data-action="apply-title-clarification">متابعة</button></div>`:''}</section>`;
 }
 const all=titleCandidates55(s),primary=s.metadata?.selectedTitle||all[0]||bestTitle55(s),show=Boolean(s.metadata?.showAltTitles),alts=all.filter(x=>x!==primary).slice(0,2);
 return `<section class="card titleStep"><button class="linkBtn" data-action="go-goals">→ رجوع للأهداف</button><div class="stepBadge">الخطوة الثالثة</div><h1>عنوان الوثيقة</h1><p class="lead">هذا أفضل عنوان بناه المحرك من نوع العمل والأهداف التي اخترتها.</p><div class="recommendedTitle"><small>العنوان الموصى به</small><div class="recommendedText">${esc(primary)}</div><button class="btn primary fullBtn" data-title-accept="${esc(primary)}">اعتماد العنوان والمتابعة</button></div><div class="titleActions"><button class="btn" data-action="toggle-alt-titles">${show?'إخفاء الاقتراحات':'عرض اقتراحات أخرى'}</button><button class="btn" data-action="edit-title55">تعديل العنوان</button></div>${show&&alts.length?`<div class="altTitlePanel"><small>اقتراحات أخرى</small>${alts.map(x=>`<button class="altTitleRow" data-title-choice55="${esc(x)}">${esc(x)}</button>`).join('')}</div>`:''}${s.metadata?.editTitle55?`<div class="editPanel"><label class="fullField"><span>اكتب العنوان الذي تريده</span><input id="workTitle55" value="${esc(primary)}"></label><button class="btn primary fullBtn" data-action="accept-manual-title55">اعتماد العنوان المعدل</button></div>`:''}</section>`;
}
