import {esc} from './engine.js';
import {bestTitle55,titleCandidates55,needsTitleClarification,clarificationOptions} from './title55.js';
export function titlePage55(s){
 if(needsTitleClarification(s)){
  const opts=clarificationOptions(s);
  return `<section class="card"><button class="linkBtn" data-action="go-goals">→ رجوع</button><div class="muted">الخطوة الثالثة</div><h1>أحتاج توضيحًا واحدًا</h1><p class="lead">الوصف الأول لا يوضح عملًا منفذًا بشكل كافٍ، لذلك لن أخترع عنوانًا. ماذا تقصد؟</p><div class="chips choiceGrid">${opts.map(x=>`<button class="chip" data-title-clarify="${esc(x)}">${esc(x)}</button>`).join('')}<button class="chip" data-action="custom-title-clarification">شيء آخر</button></div>${s.metadata?.showCustomTitleClarification?`<label class="fullField"><span>اكتب العمل باختصار</span><input id="titleClarification" value="${esc(s.metadata?.titleClarification||'')}" placeholder="مثال: تحليل نتائج اختبار الفترة الأولى"></label><div class="row"><button class="btn primary" data-action="apply-title-clarification">متابعة</button></div>`:''}</section>`;
 }
 const all=titleCandidates55(s),primary=s.metadata?.selectedTitle||all[0]||bestTitle55(s),show=Boolean(s.metadata?.showAltTitles),alts=all.filter(x=>x!==primary).slice(0,2);
 return `<section class="card"><button class="linkBtn" data-action="go-goals">→ رجوع</button><div class="muted">الخطوة الثالثة</div><h1>العنوان المقترح</h1><p class="lead">بُني بعد فهم العمل وتصنيفه واختيار أهدافه.</p><div class="titleDecision"><div class="titlePrimary">${esc(primary)}</div><button class="btn primary" data-title-accept="${esc(primary)}">اعتماد والمتابعة</button></div>${show&&alts.length?`<div class="chooser"><small>اقتراحات أخرى</small><div class="chips choiceGrid">${alts.map(x=>`<button class="chip" data-title-choice55="${esc(x)}">${esc(x)}</button>`).join('')}</div></div>`:''}<div class="row"><button class="btn" data-action="toggle-alt-titles">${show?'إخفاء الاقتراحات':'اقتراح عنوان آخر'}</button><button class="btn" data-action="edit-title55">تعديل العنوان</button></div>${s.metadata?.editTitle55?`<label class="fullField"><span>تعديل العنوان</span><input id="workTitle55" value="${esc(primary)}"></label><div class="row"><button class="btn primary" data-action="accept-manual-title55">اعتماد العنوان المعدل</button></div>`:''}</section>`;
}
