import {esc} from './engine.js';
import {bestTitle62,titleCandidates62,needsTitleClarification62,clarificationOptions62} from './title62.js';
import {runTitle62SelfTests} from './title62-selftest.js';
const ENGINE_FAILURES=runTitle62SelfTests();
export function titlePage62(s){
 if(ENGINE_FAILURES.length){console.error('Title62 self-test failures',ENGINE_FAILURES);return `<section class="card titleStep"><button class="linkBtn" data-action="go-goals">→ رجوع للأهداف</button><div class="stepBadge">الخطوة الثالثة</div><h1>العنوان يحتاج مراجعة</h1><p class="lead">أوقف المحرك الاقتراح التلقائي لأن فحص الجودة الداخلي لم ينجح. اكتب عنوانًا مختصرًا بدل عرض اقتراح غير موثوق.</p><div class="editPanel"><label class="fullField"><span>العنوان</span><input id="workTitle55" value="${esc(s.metadata?.workTitle||'')}"></label><button class="btn primary fullBtn" data-action="accept-manual-title55">اعتماد العنوان</button></div></section>`}
 if(needsTitleClarification62(s)){
  const opts=clarificationOptions62(s);
  return `<section class="card titleStep"><button class="linkBtn" data-action="go-goals">→ رجوع للأهداف</button><div class="stepBadge">الخطوة الثالثة</div><h1>حدد موضوع العمل</h1><p class="lead">لم أستطع تحديد موضوع مهني صالح للعنوان بثقة. اختر الأقرب، أو اكتب الموضوع بكلمات قليلة.</p><div class="clarifyList">${opts.map(x=>`<button class="choiceRow" data-title-clarify="${esc(x)}"><span>${esc(x)}</span><span>←</span></button>`).join('')}<button class="choiceRow" data-action="custom-title-clarification"><span>موضوع آخر</span><span>+</span></button></div>${s.metadata?.showCustomTitleClarification?`<div class="editPanel"><label class="fullField"><span>موضوع العمل فقط</span><input id="titleClarification" value="${esc(s.metadata?.titleClarification||'')}" placeholder="مثال: توظيف التقنية في التدريس"></label><button class="btn primary fullBtn" data-action="apply-title-clarification">بناء العنوان</button></div>`:''}</section>`;
 }
 const all=titleCandidates62(s),primary=s.metadata?.selectedTitle||all[0]||bestTitle62(s),show=Boolean(s.metadata?.showAltTitles),alts=all.filter(x=>x!==primary).slice(0,2);
 return `<section class="card titleStep"><button class="linkBtn" data-action="go-goals">→ رجوع للأهداف</button><div class="stepBadge">الخطوة الثالثة</div><h1>عنوان الوثيقة</h1><p class="lead">بُني العنوان من نوع الوثيقة والموضوع والفئة التي فهمها المحرك، وليس من نسخ عبارتك أو أهدافك.</p><div class="recommendedTitle"><small>العنوان الموصى به</small><div class="recommendedText">${esc(primary)}</div><button class="btn primary fullBtn" data-title-accept="${esc(primary)}">اعتماد العنوان والمتابعة</button></div><div class="titleActions"><button class="btn" data-action="toggle-alt-titles">${show?'إخفاء الاقتراحات':'عرض اقتراحات أخرى'}</button><button class="btn" data-action="edit-title55">تعديل العنوان</button></div>${show&&alts.length?`<div class="altTitlePanel"><small>بدائل سليمة</small>${alts.map(x=>`<button class="altTitleRow" data-title-choice55="${esc(x)}">${esc(x)}</button>`).join('')}</div>`:''}${s.metadata?.editTitle55?`<div class="editPanel"><label class="fullField"><span>تعديل العنوان</span><input id="workTitle55" value="${esc(primary)}"></label><button class="btn primary fullBtn" data-action="accept-manual-title55">اعتماد العنوان المعدل</button></div>`:''}</section>`;
}
