const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const clean=s=>String(s||'').replace(/\s+/g,' ').trim();
const mem=k=>{try{return sessionStorage.getItem('v94_'+k)||''}catch{return''}};
function grade(){const x=mem('grade');for(const n of ['الأول','الثاني','الثالث','الرابع','الخامس','السادس'])if(x.includes(n))return n;return''}
function stageAdj(){const x=mem('stage');if(x.includes('ابتد'))return'الابتدائي';if(x.includes('متوسط'))return'المتوسط';if(x.includes('ثانو'))return'الثانوي';return''}
function target(){const g=grade(),s=stageAdj();return g&&s?`طلاب الصف ${g} ${s}`:'الطلاب'}
function raw(){return mem('raw')||''}
function subject(){return mem('subjects').split('|||').filter(Boolean)[0]||''}
function topic(){const r=raw();const P=[[/خط|كتابة/,'الخط والكتابة'],[/قراء|فهم قرائي/,'القراءة والفهم القرائي'],[/كسور/,'الكسور'],[/جدول الضرب|الضرب/,'جدول الضرب'],[/معادلات/,'المعادلات'],[/تجرب|مختبر/,'التجارب والاستقصاء العلمي'],[/مفردات|vocabulary/i,'المفردات'],[/تحدث|speaking/i,'التحدث'],[/استماع|listening/i,'الاستماع'],[/أمن|امن|سلامة|إخلاء/,'الأمن والسلامة'],[/وطن|هوية/,'الهوية الوطنية'],[/سلوك|انضباط/,'السلوك والانضباط']];for(const[p,t]of P)if(p.test(r))return t;return subject()||'العمل المستهدف'}
function formalTopic(t){const M={'الخط والكتابة':'تحسين مهارات الخط والكتابة','القراءة والفهم القرائي':'تنمية مهارات القراءة والفهم القرائي','جدول الضرب':'تنمية مهارات جدول الضرب','الكسور':'تنمية مهارات الكسور','المعادلات':'تنمية مهارات حل المعادلات','التجارب والاستقصاء العلمي':'تنمية مهارات التجريب والاستقصاء العلمي','المفردات':'تنمية الثروة اللغوية والمفردات','التحدث':'تنمية مهارات التحدث','الاستماع':'تنمية مهارات الاستماع','الأمن والسلامة':'تعزيز الوعي بالأمن والسلامة','الهوية الوطنية':'تعزيز الهوية الوطنية','السلوك والانضباط':'تعزيز السلوك والانضباط'};return M[t]||t}
function candidates(){const f=mem('family'),sub=mem('subtype')||'',t=topic(),tar=target();let formal='',direct='',creative='';if(f==='برنامج / فعالية'){const kind=sub||'برنامج';formal=`${kind} ${formalTopic(t)} لدى ${tar}`;direct=t==='الخط والكتابة'?`تحسين خط ${tar}`:`${t} لدى ${tar}`;if(t==='الخط والكتابة')creative=kind==='مسابقة'?'أجمل خط':kind==='مبادرة'?'خطي أجمل':'خطي أجمل';else if(t.includes('القراءة'))creative=kind==='مسابقة'?'قارئ متميز':'أقرأ بطلاقة';else if(t==='جدول الضرب')creative=kind==='مسابقة'?'أبطال الضرب':'أتقن الضرب';else if(t==='الكسور')creative='أبطال الكسور';else if(t==='التجارب والاستقصاء العلمي')creative=kind==='مسابقة'?'تحدي العالم الصغير':'مختبري الصغير'}else if(f==='تحليل نتائج'){formal=`تحليل نتائج ${subject()||'المادة'} لدى ${tar}`;direct=`تحليل أداء ${tar} في ${subject()||t}`}else if(f==='تطوير مهني'){formal=`${sub||'برنامج تطوير مهني'} في ${formalTopic(t)}`;direct=`تطوير الممارسات في ${subject()||t}`}else if(f==='اجتماع / متابعة إدارية'){formal=`${sub||'اجتماع'} بشأن ${t}`;direct=`مراجعة ${t}`}else if(f==='خطة'){formal=`${sub||'خطة'} ${formalTopic(t)}`;direct=`خطة ${t}`}else{formal=`${sub||f||'وثيقة'} ${t}`;direct=t}return[formal,direct,creative].map(clean).filter((x,i,a)=>x&&a.indexOf(x)===i)}
function apply(root){const h=$('h1',root);if(!h||clean(h.textContent)!=='عنوان الوثيقة')return;const card=h.closest('.card')||root;const sig=`${mem('family')}|${mem('subtype')}|${subject()}|${topic()}|${mem('grade')}|${mem('stage')}`;if(card.dataset.title98===sig)return;card.dataset.title98=sig;const list=candidates();if(!list.length)return;const host=$('.titleChoices94,.recommendedTitle',card);if(host){const labels=['موصى به للتوثيق','مختصر وواضح','عنوان جاذب'];host.outerHTML=`<div class="titleChoices94">${list.map((x,i)=>`<button class="titleChoice94 ${i===0?'primary94':''}" data-title-accept="${x}"><small>${labels[i]||'اقتراح'}</small><b>${x}</b></button>`).join('')}</div>`}const actions=$('.titleActions',card);if(actions){$$('[data-action="toggle-alt-titles"]',actions).forEach(x=>x.remove())}const lead=$('.lead',card);if(lead)lead.textContent='اختر العنوان الأنسب، أو عدّله بنفسك. الاقتراح الأول رسمي للتوثيق، والثاني مباشر، والثالث جاذب عندما يناسب نوع العمل.'}
export function installTitle98(root=document){const run=()=>requestAnimationFrame(()=>apply(root));new MutationObserver(run).observe(root,{childList:true,subtree:true});apply(root)}
