import {buildCanonicalContext106} from './canonical-context106.js?v=106';
const clean=v=>String(v??'').replace(/\s+/g,' ').replace(/\s+([،؛:.])/g,'$1').trim();
const uniq=a=>[...new Set(a.map(clean).filter(Boolean))];
function target(c){const g=(c.education.grades||[]).join(' و');if(g)return`طلاب ${g}`;const a=(c.education.audiences||[]).filter(x=>x!=='الطلاب');return a[0]||((c.education.audiences||[]).includes('الطلاب')?'الطلاب':'')}
function focus(c){return c.education.skill.value||c.education.topic.value||c.education.branch.value||c.education.subject.value||''}
function kind(c){return c.document.subtype.value||c.document.family.value||''}
function valid(x){x=clean(x);if(x.length<5||x.length>96)return false;if(/[؟?]/.test(x))return false;if(/^(هل|كيف|وش|ايش|لماذا|ليش)\b/.test(x))return false;if(/\b(نفذت|نفذنا|سويت|سوينا|عملت|عملنا)\b/.test(x))return false;if(/\b(لمدة|بهدف|داخل المدرسة|خارج المدرسة)\b/.test(x))return false;return true}
function concept(f){const x=clean(f);if(/خط|كتابة/.test(x))return{formal:'تحسين الخط العربي والمهارات الكتابية',direct:'تحسين الخط العربي',creative:'خطي أجمل'};if(/فهم قرائي|قراءة/.test(x))return{formal:'تنمية مهارات القراءة والفهم القرائي',direct:'تنمية مهارات القراءة',creative:'قارئ اليوم'};if(/تلاوة/.test(x))return{formal:'تنمية مهارات تلاوة القرآن الكريم',direct:'تلاوة القرآن الكريم',creative:'رتّل وارتقِ'};if(/تجويد/.test(x))return{formal:'تنمية مهارات التجويد',direct:'إتقان أحكام التجويد',creative:'تلاوة متقنة'};if(/حفظ.*قرآن|القرآن الكريم/.test(x))return{formal:'تعزيز التعلم المرتبط بالقرآن الكريم',direct:'القرآن الكريم',creative:'مع القرآن'};if(/توحيد المقامات/.test(x))return{formal:'تنمية مهارة توحيد المقامات',direct:'إتقان توحيد المقامات',creative:'مقامات متقنة'};if(/كسور/.test(x))return{formal:'تنمية مهارات الكسور',direct:'إتقان الكسور',creative:'كسور بلا تعثر'};if(/تجرب|استقصاء/.test(x))return{formal:'تنمية مهارات الاستقصاء والتجريب العلمي',direct:'التجريب العلمي',creative:'مختبرنا يكتشف'};if(/برمج/.test(x))return{formal:'تنمية مهارات البرمجة',direct:'تطبيق مهارات البرمجة',creative:'أبرمج فكرتي'};if(/مواطن|هوية وطنية/.test(x))return{formal:'تعزيز المواطنة والهوية الوطنية',direct:'المواطنة والهوية الوطنية',creative:'هويتي مسؤوليتي'};return{formal:`تنمية ${x}`,direct:x,creative:x}}
function program(c){const k=kind(c)||'برنامج',f=focus(c),t=target(c);if(!f)return[];const m=concept(f),formal=t?`${k} ${m.formal} لدى ${t}`:`${k} ${m.formal}`,direct=t?`${m.direct} لدى ${t}`:m.direct;let creative=m.creative;if(/مبادرة/.test(k))creative=`مبادرة «${m.creative}»`;else if(/مسابقة/.test(k))creative=`مسابقة «${m.creative}»`;else if(/فعالية/.test(k))creative=`فعالية «${m.creative}»`;else creative=`${k} «${m.creative}»`;return[formal,direct,creative]}
function analysis(c){const f=focus(c)||'الأداء',t=target(c)||'الطلاب',m=concept(f);return[`تحليل نتائج ${m.direct} لدى ${t}`,`تحليل مستوى الأداء في ${m.direct}`,`قراءة تحليلية لنتائج ${m.direct}`]}
function plan(c){const k=kind(c)||'خطة',f=focus(c)||'التحسين',t=target(c),m=concept(f);return[t?`${k} ${m.formal} لدى ${t}`:`${k} ${m.formal}`,`${k} في ${m.direct}`,`خطة تحسين ${m.direct}`]}
function meeting(c){const f=focus(c)||c.details.purpose.value||'العمل المدرسي',k=kind(c)||'اجتماع',m=concept(f);return[`${k} بشأن ${m.direct}`,`محضر اجتماع لمناقشة ${m.direct}`,`متابعة ${m.direct}`]}
function follow(c){const f=focus(c)||'الإجراء المستهدف',k=kind(c)||'متابعة',m=concept(f);return[`${k} ${m.direct}`,`سجل متابعة ${m.direct}`,`متابعة تنفيذ ${m.direct}`]}
function pd(c){const f=focus(c)||c.details.need.value||'الممارسات المهنية',k=kind(c)||'تطوير مهني',m=concept(f);return[`${k} في ${m.direct}`,`تطوير الممارسة المهنية في ${m.direct}`,`برنامج مهني حول ${m.direct}`]}
function partnership(c){const f=focus(c)||c.details.reason.value||'الشراكة المجتمعية',m=concept(f);return[`شراكة مجتمعية لدعم ${m.direct}`,`تفعيل الشراكة في ${m.direct}`,`مبادرة مجتمعية في ${m.direct}`]}
function maintenance(c){const f=focus(c)||c.details.reason.value||'المرافق والتجهيزات';return[`متابعة صيانة ${f}`,`تقرير صيانة وتجهيزات: ${f}`,`معالجة احتياج في ${f}`]}
export function titleCandidates108(state){const c=buildCanonicalContext106(state),family=c.document.family.value;let a=[];if(family==='برنامج / فعالية')a=program(c);else if(family==='تحليل نتائج')a=analysis(c);else if(family==='خطة')a=plan(c);else if(family==='اجتماع / متابعة إدارية')a=meeting(c);else if(family==='إجراء متابعة')a=follow(c);else if(family==='تطوير مهني')a=pd(c);else if(family==='شراكة مجتمعية')a=partnership(c);else if(family==='صيانة وتجهيزات')a=maintenance(c);else a=[`${kind(c)||'وثيقة'} ${focus(c)||'مدرسية'}`];return uniq(a).filter(valid).slice(0,3)}
export function bestTitle108(state){const manual=clean(state?.metadata?.workTitle);if(state?.metadata?.titleManual&&valid(manual))return manual;const selected=clean(state?.metadata?.selectedTitle);if(valid(selected))return selected;return titleCandidates108(state)[0]||kind(buildCanonicalContext106(state))||'وثيقة مدرسية'}
export function validateTitle108(v){return valid(v)}
export function titleContext108(state){const c=buildCanonicalContext106(state);return{family:c.document.family.value,subtype:c.document.subtype.value,subject:c.education.subject.value,branch:c.education.branch.value,topic:c.education.topic.value,skill:c.education.skill.value,target:target(c)}}
