import {esc,joinAr,familyOptions,subtypeOptions} from './engine.js';
const AUD=['الطلاب','المعلمون','أولياء الأمور','الإداريون','جميع منسوبي المدرسة','مستفيدون آخرون'];
const DOM=['','البرامج والأنشطة','الإدارة والمتابعة','التحصيل والتقويم','التخطيط والتحسين','الحضور والانضباط','التطوير المهني','التوجيه الطلابي','الأمن والسلامة','الشراكة المجتمعية','الجودة والتقويم الذاتي','التقنية والتحول الرقمي','القيم والهوية الوطنية'];
const STAGES=['ابتدائي','متوسط','ثانوي'];
const GRADE_MAP={
 ابتدائي:['الأول الابتدائي','الثاني الابتدائي','الثالث الابتدائي','الرابع الابتدائي','الخامس الابتدائي','السادس الابتدائي'],
 متوسط:['الأول المتوسط','الثاني المتوسط','الثالث المتوسط'],
 ثانوي:['الأول الثانوي','الثاني الثانوي','الثالث الثانوي']
};
const INSIDE=['فصل دراسي','قاعة التدريب','المسرح المدرسي','معمل أو مختبر','الساحة أو الملعب','مكتب الإدارة','مكان آخر'];
const opts=(a,v,p)=>a.map(x=>`<option value="${esc(x)}" ${x===v?'selected':''}>${esc(x||p)}</option>`).join('');
function durations(type){
 if(type==='اجتماع / متابعة إدارية'||type==='تطوير مهني')return['','أقل من ساعة','ساعة','ساعتان','نصف يوم','يوم كامل','مدة أخرى'];
 if(type==='خطة'||type==='إجراء متابعة')return['','يوم','أسبوع','عدة أسابيع','شهر','فصل دراسي','مدة أخرى'];
 return['','حصة واحدة','أكثر من حصة','يوم واحد','عدة أيام','أسبوع','مدة أخرى'];
}
function studentScope(s){if(!(s.audiences||[]).includes('الطلاب'))return'';const stage=s.stage||'';const grades=GRADE_MAP[stage]||[];return `<div class="chooser"><small>المرحلة</small><p class="questionHelp">اختر المرحلة، ثم الصف أو الصفوف المستفيدة.</p><div class="chips">${STAGES.map(x=>`<button type="button" class="chip ${stage===x?'on':''}" data-stage="${x}">${x}</button>`).join('')}</div>${stage?`<div class="chips choiceGrid" style="margin-top:10px">${grades.map(x=>`<button type="button" class="chip ${(s.grades||[]).includes(x)?'on':''}" data-grade="${esc(x)}">${esc(x)}</button>`).join('')}</div>`:''}</div>`}
function placeBlock(s){const mode=s.metadata.placeMode||'';return `<div class="chooser"><small>مكان التنفيذ</small><div class="chips"><button type="button" class="chip ${mode==='داخل المدرسة'?'on':''}" data-place-mode="داخل المدرسة">داخل المدرسة</button><button type="button" class="chip ${mode==='عن بُعد'?'on':''}" data-place-mode="عن بُعد">عن بُعد</button><button type="button" class="chip ${mode==='خارج المدرسة'?'on':''}" data-place-mode="خارج المدرسة">خارج المدرسة</button></div>${mode==='داخل المدرسة'?`<div class="chips choiceGrid" style="margin-top:10px">${INSIDE.map(x=>`<button type="button" class="chip ${s.metadata.placeChoice===x?'on':''}" data-place-choice="${esc(x)}">${esc(x)}</button>`).join('')}</div>`:''}${mode==='داخل المدرسة'&&s.metadata.placeChoice==='مكان آخر'?`<label class="fullField"><span>اكتب المكان</span><input id="customPlace" value="${esc(s.metadata.customPlace||'')}"></label>`:''}</div>`}
export function understanding55(s){const c=s.classification,suggest=s.suggestedAudiences?.length?`<p class="questionHelp">قد يكون المستفيدون: <b>${esc(joinAr(s.suggestedAudiences))}</b>. اختر للتأكيد أو التعديل.</p>`:'<p class="questionHelp">اختر المستفيدين الفعليين.</p>';return `<section class="card"><div class="muted">الخطوة الأولى</div><h1>راجع ما فهمه المحرك</h1><p class="lead">صحح البيانات فقط عند الحاجة. سنبني الأهداف والعنوان من السياق.</p><section class="classificationBlock"><div class="muted">تصنيف العمل</div><div class="chooser"><small>عائلة العمل</small><div class="chips">${familyOptions().map(x=>`<button type="button" class="chip ${x===c.type?'on':''}" data-type="${esc(x)}">${esc(x)}</button>`).join('')}</div></div><div class="chooser"><small>النوع الفرعي</small><div class="chips">${subtypeOptions(s).map(x=>`<button type="button" class="chip ${x===c.subtype?'on':''}" data-subtype="${esc(x)}">${esc(x)}</button>`).join('')}</div></div><label class="fullField"><span>المجال</span><select id="domainSelect">${opts(DOM,c.domain||'','اختر المجال')}</select></label></section><div class="editGrid"><label><span>المنفذ</span><input id="executorName" value="${esc(s.metadata.executorName||'')}"></label><label><span>العدد</span><input id="count" inputmode="numeric" value="${esc(s.metadata.count||'')}"></label><label><span>التاريخ</span><input id="dateISO" type="date" value="${esc(s.metadata.dateISO||'')}"></label></div><div class="editGrid"><label><span>المدة</span><select id="durationSelect">${opts(durations(c.type),s.metadata.durationChoice||'','اختر المدة')}</select></label></div>${s.metadata.durationChoice==='مدة أخرى'?`<label class="fullField"><span>اكتب المدة</span><input id="customDuration" value="${esc(s.metadata.customDuration||'')}"></label>`:''}${placeBlock(s)}<div class="chooser"><small>المستفيدون</small>${suggest}<div class="chips choiceGrid">${AUD.map(x=>`<button type="button" class="chip ${(s.audiences||[]).includes(x)?'on':''}" data-audience="${esc(x)}">${esc(x)}</button>`).join('')}</div>${(s.audiences||[]).includes('مستفيدون آخرون')?`<label class="fullField"><span>من هم؟</span><input id="otherAudience" value="${esc(s.metadata.otherAudience||'')}"></label>`:''}</div>${studentScope(s)}<div class="row"><button class="btn primary" data-action="go-goals">التالي: الأهداف</button></div></section>`}
